// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Project Carmen_Inventory {
  database_type: 'PostgreSQL'
  Note: 'Carmen Inventory Project 2024 (Tenant)'
}

enum enum_activity_action {
  view
  create
  update
  delete
  login
  other
}

enum enum_activity_entity_type {
  user
  business_unit
  product
  location
  department
  unit
  currency
  exchange_rate
  menu
  delivery_point
  purchase_request
  purchase_request_item
  purchase_order
  purchase_order_item
  inventory_transaction
  inventory_adjustment
  store_requisition
  store_requisition_item
  stock_in
  stock_out
  stock_adjustment
  stock_transfer
  stock_count
  stock_take
  stock_take_item
  other
}

TABLE tb_activity {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  action enum_activity_action
  entity_type enum_activity_entity_type
  entity_id uuid
  actor_id uuid
  meta_data json [null]
  old_data json [null]
  new_data json [null]
  ip_address text [null]
  user_agent text [null]
  description text

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid

  indexes {
    (entity_type, entity_id) [name: 'activity_entitytype_entityid_idx']
  }

}

TABLE tb_menu {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  module_id uuid [not null]
  name varchar [not null]
  url varchar [not null]
  description text

  is_visible bool [default: true]
  is_active bool [default: true]
  is_lock bool [default: true]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    name [name: "menu_name_u"]
  }
}

TABLE tb_currency {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  code varchar(3) [unique, not null]
  name varchar(100) [not null]
  symbol varchar(5)
  description text [default: ""]

  is_active bool [default: true]
  exchange_rate numeric(15,5) [default: 1]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    code [name: "currency_code_u"]
  }
}

TABLE tb_exchange_rate {
  id uuid [not null, pk, default: `gen_random_uuid()`]

  at_date timestamptz [default: `now()`]
  currency_id uuid [ref: > tb_currency.id]
  exchange_rate numeric(15,5) [default: 1]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    (at_date, currency_id) [unique, name: "exchangerate_at_date_currency_u"]
  }
}

enum enum_location_type {
  inventory
  direct
  consignment
}

enum enum_location_status_type {
  active
  inactive
  maintenance
}

TABLE tb_location {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  name varchar [unique, not null]

  location_type enum_location_type [not null]

  description text
  info json [null]

  is_active bool [default: true]

  delivery_point_id uuid [ref: > tb_delivery_point.id]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    name [name: "location_name_u"]
  }
}

TABLE tb_delivery_point {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  name varchar [unique, not null]
  is_active bool [default: true]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    name [name: "deliverypoint_name_u"]
  }
}

TABLE tb_unit {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  name varchar [unique, not null]
  description text
  is_active bool [default: true]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    name [name: "unit_name_u"]
  }
}

Enum enum_unit_type {
  order_unit
  ingredient_unit
}

TABLE tb_unit_conversion {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  product_id uuid [ref: > tb_product.id]
  unit_type enum_unit_type [not null]
  from_unit_id uuid [ref: > tb_unit.id]
  from_unit_name varchar [not null]
  from_unit_qty numeric(20,5) [default: 1]
  to_unit_id uuid [ref: > tb_unit.id]
  to_unit_name varchar [not null]
  to_unit_qty numeric(20,5) [default: 1]
  is_default bool [default: false]
  description json [null, default: '{}']

  is_active bool [default: true]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    (product_id, unit_type, from_unit_id, to_unit_id) [name: "unitconversion_product_unit_type_from_unit_to_unit_u"]
  }
}

TABLE tb_department {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  name varchar [unique, not null]
  description text
  is_active bool [default: true]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    name [name: "department_name_u"]
  }
}

TABLE tb_department_user {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  user_id uuid [not null]
  department_id uuid [not null, ref: > tb_department.id]
  is_hod bool [default: false]

  indexes {
    (department_id, user_id) [unique ,name: "department_user_u"]
  }
}

TABLE tb_user_location {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  user_id uuid [not null]
  location_id uuid [not null, ref: > tb_location.id]

  indexes {
    (user_id, location_id) [unique, name: "user_location_u"]
  }
}

enum enum_product_status_type {
  active
  inactive
  discontinued
}

TABLE tb_product {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  code varchar [unique, not null]
  name varchar [unique, not null]
  local_name varchar [null]
  description text

  inventory_unit_id uuid [not null, ref: > tb_unit.id]
  inventory_unit_name varchar [not null, default: ""]

  product_status_type enum_product_status_type [not null, default: "active"]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    code [name: "product_code_u"]
    name [name: "product_name_u"]

  }
}

enum enum_tax_type {
  none
  vat
}

TABLE tb_product_info {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  product_id uuid [unique, not null, ref: - tb_product.id]
  product_item_group_id uuid [ref: > tb_product_item_group.id]

  is_ingredients bool [default: false]

  price numeric(20,5)
  tax_type enum_tax_type [default: "vat"]
  tax_rate numeric(15,5) [default: 0]
  price_deviation_limit numeric(20,5) [default: 0]

  info json [null]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    product_id [name: "productinfo_product_u"]
  }
}

TABLE tb_product_location {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  product_id uuid [not null, ref: > tb_product.id]
  location_id uuid [not null, ref: > tb_location.id]

  indexes {
    (product_id, location_id) [name : "product_location_u", unique]
  }
}



TABLE tb_product_category {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  code varchar [unique, not null]
  name varchar [unique, not null]
  description text
  is_active bool [default: true]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    code [name: "productcategory_code_u"]
    name [name: "productcategory_name_u"]
  }
}

TABLE tb_product_sub_category {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  code varchar [ not null, default: ""]
  name varchar [ not null]
  description text
  is_active bool [default: true]

  product_category_id uuid [not null,ref: > tb_product_category.id]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    (code, name,product_category_id)  [ unique, name: "productsubcategory_code_name_product_category_u"]
  }
}

TABLE tb_product_item_group {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  code varchar [ not null, default: ""]
  name varchar [ not null]

  description text
  is_active bool [default: true]

  product_subcategory_id uuid [not null, ref: > tb_product_sub_category.id]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    (code, name, product_subcategory_id) [unique, name: "productitemgroup_code_name_product_subcategory_u"]
  }
}

enum enum_workflow_type {
  purchase_request
  purchase_order
  store_requisition
}

TABLE tb_workflow {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  name varchar [unique, not null]

  workflow_type enum_workflow_type [not null]

  description text
  data json
  is_active bool [default: true]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    name [name: "workflow_name_u"]
  }
}

enum enum_purchase_request_doc_status {
  draft
  work_in_process
  complete
  complete_purchase_order
}

TABLE tb_purchase_request {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  reference_name varchar [unique, not null]

  purchase_request_date timestamptz
  workflow_id uuid [ref: > tb_workflow.id]

  workflow_obj json
  workflow_history json

  current_workflow_status varchar

  purchase_request_status enum_purchase_request_doc_status [default: 'draft']

  requestor_id uuid
  department_id uuid

  job_code varchar
  budget_code varchar
  allocated_budget_amount numeric(20,5)

  is_active bool [default: true]

  doc_version numeric [not null, default: 0]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    reference_name [name: "PR0_reference_name_u"]
  }
}

TABLE tb_purchase_request_detail {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  purchase_request_id uuid [ref: > tb_purchase_request.id]

  location_id uuid [ref: > tb_location.id]
  location_name varchar

  product_id uuid [not null, ref: > tb_product.id]
  product_name varchar
  unit_id uuid [ref: > tb_unit.id]
  unit_name varchar

  vendor_id uuid [ref: > tb_vendor.id]
  vendor_name varchar

  price_list_id uuid [ref: > tb_price_list.id]

  description text

  requested_qty numeric(20,5)
  approved_qty numeric(20,5)

  currency_id uuid [ref: > tb_currency.id]
  exchange_rate numeric(15,5)
  exchange_rate_date timestamptz

  price numeric(20,5)
  total_price numeric(20,5)
  foc numeric(20,5)

  is_tax_included bool
  is_tax_adjustment bool
  is_discount bool

  discount_rate numeric(15,5)
  discount_amount numeric(20,5)

  tax_rate numeric(15,5)
  tax_amount numeric(20,5)

  is_active bool [default: true]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    // name [name: "PR1_name_u"]
  }
}

enum enum_purchase_request_workflow_status {
  draft
  pending
  review
  accept
}

enum enum_purchase_order_doc_status {
  open 
  voided 
  closed 
  draft 
  sent
  partial
  fully_received 
  cancelled 
  deleted 
}

TABLE tb_purchase_order {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  name varchar [unique, not null]
  purchase_order_status enum_purchase_order_doc_status [default: 'open']

  description text

  order_date timestamptz
  delivery_date timestamptz

  vendor_id uuid [ref: > tb_vendor.id]
  vendor_name varchar

  currency_id uuid [ref: > tb_currency.id]
  currency_name varchar
  base_currency_id uuid [ref: > tb_currency.id]
  base_currency_name varchar

  exchange_rate numeric(15,5)
  notes text [null]

  approval_date timestamptz [null]

  email varchar
  buyer_name varchar
  credit_term varchar
  remarks text [null]

  info json

  history json

  is_active bool [default: true]

  doc_version numeric [not null, default: 0]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid
  
  indexes {
    // name [name: "PO_name_u"]
  }
}

TABLE tb_purchase_order_detail {
  id uuid [not null, pk, default: `gen_random_uuid()`]

  name varchar [unique]
  description text
  is_active bool [default: true]

  purchase_order_id uuid [ref: > tb_purchase_order.id]

  purchase_request_detail_id uuid [ref: > tb_purchase_request_detail.id]

  exchange_rate numeric(15,5)
  order_qty numeric(20,5)
  order_unit_id uuid [ref: > tb_unit.id]
  order_unit_name varchar

  base_qty numeric(20,5)
  base_unit_id uuid [ref: > tb_unit.id]
  base_unit_name varchar

  unit_price numeric(20,5)
  sub_total_price numeric(20,5)
  base_sub_total_price numeric(20,5)
  is_foc bool [default: false]
  is_tax_included bool [default: false]
  tax_rate numeric(15,5) [default: 0]
  tax_amount numeric(20,5) [default: 0]

  discount_rate numeric(15,5) [default: 0]
  discount_amount numeric(20,5) [default: 0]

  net_amount numeric(20,5) [default: 0]
  base_net_amount numeric(20,5) [default: 0]

  total_price numeric(20,5)
  base_total_price numeric(20,5)

  info json

  history json

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    // name [name: "PO1_name_u"]
  }
}


TABLE tb_vendor {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  name varchar [unique, not null]
  description text

  info json

  is_active bool [default: true]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    name [name: "vendor_name_u"]
  }
}

TABLE tb_price_list{
   id uuid [not null, pk, default: `gen_random_uuid()`]
   vendor_id uuid [ref: > tb_vendor.id]
   from_date timestamptz [not null, default: `CURRENT_TIMESTAMP`]
   to_date timestamptz [not null, default: `CURRENT_TIMESTAMP`]

   product_id uuid [not null, ref: > tb_product.id]
   product_name varchar
   price numeric(20,5) [not null]

   unit_id uuid [ref: > tb_unit.id]
   unit_name varchar

   created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
   created_by_id uuid 

   updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
   updated_by_id uuid
}

enum enum_vendor_contact_type {
  phone
  email
}


TABLE tb_vendor_contact {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  vendor_id uuid [ref: > tb_vendor.id]
  contact_type enum_vendor_contact_type [not null]
  description text
  is_active bool [default: true]

  info json [null]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    (vendor_id, contact_type) [ name: "vendorcontact_vendor_contact_type_idx"]
  }
}

enum enum_vendor_address_type {
  contact_address
  mailing_address
  register_address
}

TABLE tb_vendor_address {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  vendor_id uuid [ref: > tb_vendor.id]
  address_type enum_vendor_address_type

  address json [null]
  is_active bool [default: true]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    (vendor_id, address_type) [ name: "vendoraddress_vendor_address_type_idx"]
  }
}

TABLE tb_product_tb_vendor {
  id uuid [not null, pk, default: `gen_random_uuid()`]

  product_id uuid [not null, ref: > tb_product.id]
  product_name varchar
  vendor_id uuid [ref: > tb_vendor.id]

  vendor_product_name varchar

  description text
  is_active bool [default: true]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    (vendor_id, product_id) [unique, name: "product_vendor_vendor_product_u"]
  }
}

enum enum_inventory_doc_type {
  good_receive_note
  credit_note
  store_requisition
  stock_in
  stock_out
  stock_take
}

TABLE tb_inventory_transaction {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  // name varchar [unique, not null]
  inventory_doc_type enum_inventory_doc_type [not null]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    // name [name: "inventorytransaction_name_idx"]
  }

}

TABLE tb_inventory_transaction_detail {

  id uuid [not null, pk, default: `gen_random_uuid()`]
  inventory_transaction_id uuid [not null, ref: > tb_inventory_transaction.id]

  from_lot_name varchar
  current_lot_name varchar

  qty numeric(20,5)
  unit_cost numeric(20,5)
  total_cost numeric(20,5)

  info json [null]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

}

TABLE tb_inventory_transaction_closing_balance {

  id uuid [not null, pk, default: `gen_random_uuid()`]
  inventory_transaction_detail_id uuid [ not null, ref: - tb_inventory_transaction_detail.id]
  
  lot_name varchar
  lot_index integer [not null, default: 1]

  qty numeric(20,5)
  cost numeric(20,5)

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    (lot_name, lot_index) [unique, name: "inventorytransactionclosingbalance_lotname_lot_index_u"]
  }
}

enum enum_doc_status {
  draft
  complete
  void
}

TABLE tb_good_receive_note {

  id uuid [not null, pk, default: `gen_random_uuid()`]

  name varchar
  ref_no varchar
  doc_status enum_doc_status [not null,default: 'draft']

  workflow json [null]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

}

TABLE tb_good_receive_note_detail {

  id uuid [not null, pk, default: `gen_random_uuid()`]
  inventory_transaction_id uuid [null, ref: - tb_inventory_transaction.id]
  good_receive_note_id uuid [not null, ref: > tb_good_receive_note.id]
  
  purchase_order_detail_id uuid [not null, ref: - tb_purchase_order_detail.id]
  
  location_id uuid [not null, ref: - tb_location.id]

  product_id uuid [not null, ref: > tb_product.id]
  product_name varchar
  received_qty numeric(20,5)
  received_unit_id uuid [not null, ref: - tb_unit.id]
  received_unit_name varchar

  is_foc bool [default: false]

  price numeric(20,5)
  tax_amount numeric(20,5)
  total_amount numeric(20,5)

  delivery_point_id uuid [null, ref: - tb_delivery_point.id]

  base_price numeric(20,5)
  base_qty numeric(20,5)

  extra_cost numeric(20,5)
  total_cost numeric(20,5)

  is_discount bool [default: false]
  discount_amount numeric(20,5) 

  is_tax_adjustment bool [default: false]

  lot_number varchar
  expired_date timestamptz

  info json

  comment text [null]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

}

TABLE tb_store_requisition {

  id uuid [not null, pk, default: `gen_random_uuid()`]
  
  name varchar
  ref_no varchar
  doc_status enum_doc_status [not null,default: 'draft']

  workflow json [null]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

}

TABLE tb_store_requisition_detail {

  id uuid [not null, pk, default: `gen_random_uuid()`]
  inventory_transaction_id uuid [null, ref: - tb_inventory_transaction.id]
  store_requisition_id uuid [not null, ref: > tb_store_requisition.id]
  
  name varchar

  product_id uuid [not null, ref: > tb_product.id]
  product_name varchar
  qty numeric(20,5)

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

}


TABLE tb_stock_in {

  id uuid [not null, pk, default: `gen_random_uuid()`]
  
  name varchar
  ref_no varchar
  doc_status enum_doc_status [not null,default: 'draft']

  workflow json [null]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

}

TABLE tb_stock_in_detail {

  id uuid [not null, pk, default: `gen_random_uuid()`]
  inventory_transaction_id uuid [null, ref: - tb_inventory_transaction.id]
  stock_in_id uuid [not null, ref: > tb_stock_in.id]
  
  name varchar

  product_id uuid [not null, ref: > tb_product.id]
  product_name varchar
  qty numeric(20,5)

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

}


TABLE tb_stock_out {

  id uuid [not null, pk, default: `gen_random_uuid()`]
  
  name varchar
  ref_no varchar
  doc_status enum_doc_status [not null,default: 'draft']

  workflow json [null]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

}

TABLE tb_stock_out_detail {

  id uuid [not null, pk, default: `gen_random_uuid()`]
  inventory_transaction_id uuid [null, ref: - tb_inventory_transaction.id]
  stock_out_id uuid [not null, ref: > tb_stock_out.id]
  
  name varchar

  product_id uuid [not null, ref: > tb_product.id]
  product_name varchar
  qty numeric(20,5)

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

}

TABLE tb_credit_note {
  id uuid [not null, pk, default: `gen_random_uuid()`]

  name varchar
  ref_no varchar
  doc_status enum_doc_status [not null,default: 'draft']

  workflow json [null]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    name [name: "creditnote_name_u"]
  }
}

TABLE tb_credit_note_detail {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  inventory_transaction_id uuid [null, ref: - tb_inventory_transaction.id]
  credit_note_id uuid [not null, ref: > tb_credit_note.id]

  name varchar

  product_id uuid [not null, ref: > tb_product.id]
  product_name varchar
  qty numeric(20,5)
  amount numeric(20,5)

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    (credit_note_id, name) [unique, name: "creditnotedetail_credit_note_name_u"]
  }
}

TABLE tb_stock_take {
  id uuid [not null, pk, default: `gen_random_uuid()`]

  name varchar
  ref_no varchar
  doc_status enum_doc_status [not null,default: 'draft']

  workflow json [null]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid
}

TABLE tb_stock_take_detail {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  inventory_transaction_id uuid [null, ref: - tb_inventory_transaction.id]
  stock_take_id uuid [not null, ref: > tb_stock_take.id]

  name varchar
  
  product_id uuid [not null, ref: > tb_product.id]
  product_name varchar
  qty numeric(20,5)

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid
}

enum  enum_count_stock_type {
  physical
  spot
}

enum  enum_count_stock_status {
  draft
  in_progress
  completed
  cancelled
}


TABLE tb_count_stock {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  start_date timestamptz [not null, default: `CURRENT_TIMESTAMP` ]
  end_date timestamptz [ null]
  location_id uuid [not null]
  notes text [null]

  info json

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid
}

TABLE tb_count_stock_detail {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  count_stock_id uuid [not null, ref: > tb_count_stock.id]
  product_id uuid [not null, ref: > tb_product.id]
  product_name varchar
  qty numeric(20,5) [not null]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid
}

enum enum_jv_status {
  draft
  posted
}

TABLE tb_jv_header {
  id uuid [not null, pk, default: `gen_random_uuid()`]

  currency_id uuid [not null, ref: > tb_currency.id]
  exchange_rate numeric(15,5) [not null]
  base_currency_id uuid [not null, ref: > tb_currency.id]

  jv_type varchar(255) [not null]
  jv_number varchar(255) [not null]
  jv_date timestamptz [not null]
  jv_description text [null]
  jv_status enum_jv_status [not null]

  workflow json [null]
  info json [null]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid
}

TABLE tb_jv_detail {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  jv_header_id uuid [not null, ref: > tb_jv_header.id]

  account_department_id uuid [not null]
  // account_code uuid [not null, ref: > tb_account_code.id]
  account_name varchar [not null]

  currency_id uuid [not null, ref: > tb_currency.id]
  exchange_rate numeric(15,5) [not null]

  debit numeric(20,5) [not null, default: 0.0]
  credit numeric(20,5) [not null, default: 0.0]

  base_currency_id uuid [not null, ref: > tb_currency.id]
  base_debit numeric(20,5) [not null, default: 0.0]
  base_credit numeric(20,5) [not null, default: 0.0]

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid
}

Enum enum_comment_type {
  user
  system
}

TABLE tb_attachment {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  filename varchar(255)
  filetype varchar(255)
  data bytea
  info json
}

TABLE tb_config_running_code {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  type varchar(255)
  config json [null, default: '{}']
  
  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid
}

TABLE tb_currency_comment {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  type enum_comment_type

  user_id uuid [null]
  message text
  attachments json [null, default: '{}']

  info json

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid
}

TABLE tb_unit_comment {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  type enum_comment_type

  user_id uuid [null]
  message text
  attachments json [null, default: '{}']

  info json

  created_at timestamptz [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamptz [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid
}
 