#version: '3.8'

services:
  frontend:
    container_name: carmen-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3500:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://dev-api:4000
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge