export const API_URL = process.env.API_URL
export const tenantId = process.env.X_TENANT_ID
export const mockToken =
    `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA0MzhmZjQ0LTc1NGYtNDJiZC05NWI1LTUzYWFlMjBkZWMzZSIsInVzZXJuYW1lIjoidGVzdDEiLCJpYXQiOjE3MzAzNjMyNTYsImV4cCI6MTczMDM2Njg1Nn0.pSQwnIIqSjoEqnPKvYgq7d9K536HCgl0_P7a5-g-6N0`