import { LucideIconName } from '@/components/Sidebar/NewSidebar';
import * as m from '@/paraglide/messages.js';

export const menuItems = [
	{
		title: `${m.dashboard()}`,
		path: '/dashboard',
		icon: 'LayoutDashboard' as LucideIconName,
		visible: true,
		enabled: true,
		subItems: [],
	},
	{
		title: `${m.Procurement()}`,
		path: '/procurement',
		icon: 'ShoppingCart' as LucideIconName,
		visible: true,
		enabled: true,
		subItems: [
			{
				name: `${m.my_approvals()}`,
				path: '/procurement/my-approvals',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.purchase_requests()}`,
				path: '/procurement/purchase-requests',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.purchase_orders()}`,
				path: '/procurement/purchase-orders',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.goods_received_note()}`,
				path: '/procurement/goods-received-note',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.credit_notes()}`,
				path: '/procurement/credit-note',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.purchase_request_templates()}`,
				path: '/procurement/purchase-request-templates',
				visible: true,
				enabled: true,
			},
		],
	},
	{
		title: `${m.product_management()}`,
		path: '/product-management',
		icon: 'Package' as LucideIconName,
		visible: true,
		enabled: true,
		subItems: [
			{
				name: `${m.products()}`,
				path: '/product-management/products',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.categories()}`,
				path: '/product-management/categories',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.reports()}`,
				path: '/product-management/reports',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.unit()}`,
				path: '/product-management/unit',
				visible: true,
				enabled: true,
			},
		],
	},
	{
		title: `${m.vendor_management()}`,
		path: '/vendor-management',
		icon: 'Users' as LucideIconName,
		visible: true,
		enabled: true,
		subItems: [
			{
				name: `${m.manage_vendors()}`,
				path: '/vendor-management/vendors',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.price_lists()}`,
				path: '/vendor-management/price-lists',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.price_comparisons()}`,
				path: '/vendor-management/price-comparisons',
				visible: true,
				enabled: true,
			},
		],
	},

	{
		title: `${m.store_operations()}`,
		path: '/store-operations',
		icon: 'Store' as LucideIconName,
		visible: true,
		enabled: true,
		subItems: [
			{
				name: `${m.store_requisitions()}`,
				path: '/store-operations/store-requisitions',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.stock_replenishment()}`,
				path: '/store-operations/stock-replenishment',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.wastage_reporting()}`,
				path: '/store-operations/wastage-reporting',
				visible: true,
				enabled: true,
			},
		],
	},
	{
		title: `${m.inventory_management()}`,
		path: '/inventory-management',
		icon: 'Package' as LucideIconName,
		visible: true,
		enabled: true,
		subItems: [
			{
				name: `${m.stock_overview()}`,
				path: '/inventory-management/stock-overview',
				visible: true,
				enabled: true,
			},
			{
				name: 'Inventory Adjustments',
				path: '/inventory-management/inventory-adjustments',
				visible: true,
				enabled: true,
			},

			{
				name: 'Spot Check',
				path: '/inventory-management/spot-check',
				visible: true,
				enabled: true,
			},
			{
				name: 'Physical Count',
				path: '/inventory-management/physical-count-management',
				visible: true,
				enabled: true,
			},

			{
				name: 'Period End',
				path: '/inventory-management/period-end',
				visible: true,
				enabled: true,
			},
		],
	},
	{
		title: `${m.operational_planning()}`,
		path: '/operational-planning',
		icon: 'CalendarClock' as LucideIconName,
		visible: true,
		enabled: true,
		subItems: [
			{
				name: `${m.recipes_management()}`,
				path: '/operational-planning/recipes-management',
				subItems: [
					{
						name: `${m.recipe_library()}`,
						path: '/operational-planning/recipe-management/recipes',
					},
					{
						name: `${m.categories()}`,
						path: '/operational-planning/recipe-management/categories',
					},
					{
						name: `${m.recipe_cuisine_types()}`,
						path: '/operational-planning/recipe-management/cuisine-types',
					},
				],
				visible: true,
				enabled: true,
			},
			{
				name: `${m.menu_engineering()}`,
				path: '/operational-planning/menu-engineering',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.demand_forecasting()}`,
				path: '/operational-planning/demand-forecasting',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.inventory_planning()}`,
				path: '/operational-planning/inventory-planning',
				visible: true,
				enabled: true,
			},
		],
	},
	{
		title: `${m.production()}`,
		path: '/production',
		icon: 'Factory' as LucideIconName,
		visible: true,
		enabled: true,
		subItems: [
			{
				name: `${m.recipe_execution()}`,
				path: '/production/recipe-sexecution',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.batch_production()}`,
				path: '/production/batch-production',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.wastage_tracking()}`,
				path: '/production/wastage-tracking',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.quality_control()}`,
				path: '/production/quality-control',
				visible: true,
				enabled: true,
			},
		],
	},
	{
		title: `${m.reporting_and_analytics()}`,
		path: '/reporting-analytics',
		icon: 'BarChart2' as LucideIconName,
		visible: true,
		enabled: true,
		subItems: [
			{
				name: `${m.operational_reports()}`,
				path: '/reporting-analytics/operational-reports',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.financial_reports()}`,
				path: '/reporting-analytics/financial-reports',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.inventory_reports()}`,
				path: '/reporting-analytics/inventory-reports',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.vendor_performance()}`,
				path: '/reporting-analytics/vendor-performance',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.cost_analysis()}`,
				path: '/reporting-analytics/cost-analysis',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.sales_analysis()}`,
				path: '/reporting-analytics/sales-analysis',
				visible: true,
				enabled: true,
			},
		],
	},
	{
		title: `${m.finance()}`,
		path: '/finance',
		icon: 'DollarSign' as LucideIconName,
		visible: true,
		enabled: true,
		subItems: [
			{
				name: `${m.account_code_mapping()}`,
				path: '/finance/account-code-mapping',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.exchange_rates()}`,
				path: '/finance/exchange-rates',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.budget_planning_and_control()}`,
				path: '/finance/budget-planning-and-control',
				visible: true,
				enabled: true,
			},
		],
	},
	{
		title: `${m.configuration()}`,
		path: '/configuration',
		icon: 'MonitorCog' as LucideIconName,
		visible: true,
		enabled: true,
		subItems: [
			{
				name: `${m.currency()}`,
				path: '/configuration/currency',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.delivery_point()}`,
				path: '/configuration/delivery-point',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.store_location()}`,
				path: '/configuration/locations',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.department()}`,
				path: '/configuration/department',
				visible: true,
				enabled: true,
			},
		],
	},
	{
		title: `${m.system_administration()}`,
		path: '/system-administration',
		icon: 'Settings' as LucideIconName,
		visible: true,
		enabled: true,
		subItems: [
			{
				name: `${m.user_management()}`,
				path: '/system-administration/user-management',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.system_configuration()}`,
				path: '/system-administration/config',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.location_management()}`,
				path: '/system-administration/location-management',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.workflow_management()}`,
				path: '/system-administration/workflow-management',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.general_settings()}`,
				path: '/system-administration/general-settings',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.notification_preferences()}`,
				path: '/system-administration/notification-preferences',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.license_management()}`,
				path: '/system-administration/license-management',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.security_settings()}`,
				path: '/system-administration/security-settings',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.data_backup_and_recovery()}`,
				path: '/system-administration/data-backup-and-recovery',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.system_integrations()}`,
				path: '/system-administration/system-integrations',
				visible: true,
				enabled: true,
			},
		],
	},
	{
		title: `${m.help_and_support()}`,
		path: '/help-support',
		icon: 'HelpCircle' as LucideIconName,
		visible: true,
		enabled: true,
		subItems: [
			{
				name: `${m.user_manuals()}`,
				path: '/help-support/user-manuals',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.video_tutorials()}`,
				path: '/help-support/video-tutorials',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.faqs()}`,
				path: '/help-support/faqs',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.support_ticket_system()}`,
				path: '/help-support/support-ticket-system',
				visible: true,
				enabled: true,
			},
			{
				name: `${m.system_updates_and_release_notes()}`,
				path: '/help-support/system-updates-and-release-notes',
				visible: true,
				enabled: true,
			},
		],
	},
];
