import { RecipeCuisine } from '@/dtos/cuisine-types.dto';
import { RecipeCategory } from '@/dtos/recipe-category.dto';

export const mockCuisines: RecipeCuisine[] = [
	{
		id: '1',
		name: 'Italian',
		code: 'ITA',
		description: 'Traditional Italian cuisine with regional specialties',
		region: 'Europe',
		status: 'active',
		sortOrder: 1,
		recipeCount: 45,
		activeRecipeCount: 38,
		popularDishes: ['Pizza', 'Pasta', 'Risotto'],
		keyIngredients: ['Olive Oil', 'Tomatoes', 'Basil'],
		lastUpdated: '2024-01-15',
	},
	{
		id: '2',
		name: 'Chinese',
		code: 'CHN',
		description: 'Diverse Chinese culinary traditions',
		region: 'Asia',
		status: 'active',
		sortOrder: 2,
		recipeCount: 60,
		activeRecipeCount: 52,
		popularDishes: ['Dim Sum', 'Noodles', 'Stir Fry'],
		keyIngredients: ['Soy Sauce', 'Ginger', 'Garlic'],
		lastUpdated: '2024-01-14',
	},
	{
		id: '3',
		name: 'Mexican',
		code: 'MEX',
		description: 'Vibrant Mexican food culture',
		region: 'Americas',
		status: 'active',
		sortOrder: 3,
		recipeCount: 35,
		activeRecipeCount: 30,
		popularDishes: ['Tacos', 'Enchiladas', 'Guacamole'],
		keyIngredients: ['Corn', 'Chili', 'Cilantro'],
		lastUpdated: '2024-01-15',
	},
	{
		id: '4',
		name: 'Indian',
		code: 'IND',
		description: 'Rich and diverse Indian cuisine',
		region: 'Asia',
		status: 'active',
		sortOrder: 4,
		recipeCount: 50,
		activeRecipeCount: 45,
		popularDishes: ['Curry', 'Biryani', 'Tandoori'],
		keyIngredients: ['Spices', 'Rice', 'Yogurt'],
		lastUpdated: '2024-01-13',
	},
	{
		id: '5',
		name: 'French',
		code: 'FRA',
		description: 'Classic French culinary arts',
		region: 'Europe',
		status: 'active',
		sortOrder: 5,
		recipeCount: 40,
		activeRecipeCount: 35,
		popularDishes: ['Coq au Vin', 'Ratatouille', 'Croissant'],
		keyIngredients: ['Butter', 'Wine', 'Herbs'],
		lastUpdated: '2024-01-15',
	},
	{
		id: '6',
		name: 'Japanese',
		code: 'JPN',
		description: 'Traditional Japanese cooking methods',
		region: 'Asia',
		status: 'active',
		sortOrder: 6,
		recipeCount: 55,
		activeRecipeCount: 48,
		popularDishes: ['Sushi', 'Ramen', 'Tempura'],
		keyIngredients: ['Rice', 'Seaweed', 'Dashi'],
		lastUpdated: '2024-01-14',
	},
	{
		id: '7',
		name: 'Mediterranean',
		code: 'MED',
		description: 'Healthy Mediterranean diet',
		region: 'Europe',
		status: 'active',
		sortOrder: 7,
		recipeCount: 30,
		activeRecipeCount: 25,
		popularDishes: ['Greek Salad', 'Hummus', 'Falafel'],
		keyIngredients: ['Olive Oil', 'Lemon', 'Chickpeas'],
		lastUpdated: '2024-01-15',
	},
	{
		id: '8',
		name: 'Thai',
		code: 'THA',
		description: 'Flavorful Thai cooking traditions',
		region: 'Asia',
		status: 'active',
		sortOrder: 8,
		recipeCount: 45,
		activeRecipeCount: 40,
		popularDishes: ['Pad Thai', 'Green Curry', 'Tom Yum'],
		keyIngredients: ['Lemongrass', 'Coconut Milk', 'Fish Sauce'],
		lastUpdated: '2024-01-15',
	},
];

export const mockCategories: RecipeCategory[] = [
	{
		id: '1',
		name: 'Appetizers',
		code: 'APP',
		description: 'Small dishes served before main courses',
		parentId: null,
		level: 1,
		status: 'active',
		sortOrder: 1,
		defaultCostSettings: {
			laborCostPercentage: 30,
			overheadPercentage: 20,
			targetFoodCostPercentage: 30,
		},
		defaultMargins: {
			minimumMargin: 65,
			targetMargin: 70,
		},
		recipeCount: 45,
		activeRecipeCount: 38,
		averageCost: 4.5,
		averageMargin: 68.5,
		lastUpdated: '2024-01-15',
	},
	{
		id: '1-1',
		name: 'Cold Appetizers',
		code: 'APP-COLD',
		description: 'Appetizers served cold or at room temperature',
		parentId: '1',
		level: 2,
		status: 'active',
		sortOrder: 1,
		defaultCostSettings: {
			laborCostPercentage: 25,
			overheadPercentage: 18,
			targetFoodCostPercentage: 28,
		},
		defaultMargins: {
			minimumMargin: 68,
			targetMargin: 72,
		},
		recipeCount: 20,
		activeRecipeCount: 18,
		averageCost: 3.75,
		averageMargin: 70.2,
		lastUpdated: '2024-01-14',
	},
	{
		id: '1-2',
		name: 'Hot Appetizers',
		code: 'APP-HOT',
		description: 'Appetizers served hot',
		parentId: '1',
		level: 2,
		status: 'active',
		sortOrder: 2,
		defaultCostSettings: {
			laborCostPercentage: 35,
			overheadPercentage: 22,
			targetFoodCostPercentage: 32,
		},
		defaultMargins: {
			minimumMargin: 62,
			targetMargin: 68,
		},
		recipeCount: 25,
		activeRecipeCount: 20,
		averageCost: 5.25,
		averageMargin: 66.8,
		lastUpdated: '2024-01-15',
	},
	{
		id: '2',
		name: 'Main Courses',
		code: 'MAIN',
		description: 'Primary dishes for a meal',
		parentId: null,
		level: 1,
		status: 'active',
		sortOrder: 2,
		defaultCostSettings: {
			laborCostPercentage: 35,
			overheadPercentage: 25,
			targetFoodCostPercentage: 32,
		},
		defaultMargins: {
			minimumMargin: 60,
			targetMargin: 65,
		},
		recipeCount: 80,
		activeRecipeCount: 65,
		averageCost: 12.5,
		averageMargin: 63.5,
		lastUpdated: '2024-01-15',
	},
	{
		id: '2-1',
		name: 'Meat Dishes',
		code: 'MAIN-MEAT',
		description: 'Main courses featuring meat as primary ingredient',
		parentId: '2',
		level: 2,
		status: 'active',
		sortOrder: 1,
		defaultCostSettings: {
			laborCostPercentage: 32,
			overheadPercentage: 23,
			targetFoodCostPercentage: 35,
		},
		defaultMargins: {
			minimumMargin: 58,
			targetMargin: 63,
		},
		recipeCount: 30,
		activeRecipeCount: 25,
		averageCost: 15.75,
		averageMargin: 61.2,
		lastUpdated: '2024-01-14',
	},
	{
		id: '2-2',
		name: 'Seafood',
		code: 'MAIN-FISH',
		description: 'Main courses featuring seafood',
		parentId: '2',
		level: 2,
		status: 'active',
		sortOrder: 2,
		defaultCostSettings: {
			laborCostPercentage: 30,
			overheadPercentage: 20,
			targetFoodCostPercentage: 38,
		},
		defaultMargins: {
			minimumMargin: 55,
			targetMargin: 60,
		},
		recipeCount: 25,
		activeRecipeCount: 20,
		averageCost: 18.5,
		averageMargin: 58.5,
		lastUpdated: '2024-01-15',
	},
	{
		id: '2-3',
		name: 'Vegetarian',
		code: 'MAIN-VEG',
		description: 'Vegetarian main courses',
		parentId: '2',
		level: 2,
		status: 'active',
		sortOrder: 3,
		defaultCostSettings: {
			laborCostPercentage: 35,
			overheadPercentage: 25,
			targetFoodCostPercentage: 28,
		},
		defaultMargins: {
			minimumMargin: 65,
			targetMargin: 70,
		},
		recipeCount: 25,
		activeRecipeCount: 20,
		averageCost: 8.25,
		averageMargin: 68.5,
		lastUpdated: '2024-01-13',
	},
	{
		id: '3',
		name: 'Desserts',
		code: 'DES',
		description: 'Sweet dishes served after main courses',
		parentId: null,
		level: 1,
		status: 'active',
		sortOrder: 3,
		defaultCostSettings: {
			laborCostPercentage: 40,
			overheadPercentage: 25,
			targetFoodCostPercentage: 25,
		},
		defaultMargins: {
			minimumMargin: 70,
			targetMargin: 75,
		},
		recipeCount: 35,
		activeRecipeCount: 30,
		averageCost: 3.75,
		averageMargin: 72.5,
		lastUpdated: '2024-01-15',
	},
	{
		id: '3-1',
		name: 'Ice Cream',
		code: 'DES-ICE',
		description: 'Ice cream desserts',
		parentId: '3',
		level: 2,
		status: 'active',
		sortOrder: 1,
		defaultCostSettings: {
			laborCostPercentage: 40,
			overheadPercentage: 25,
			targetFoodCostPercentage: 25,
		},
		defaultMargins: {
			minimumMargin: 70,
			targetMargin: 75,
		},
		recipeCount: 15,
		activeRecipeCount: 12,
		averageCost: 2.5,
		averageMargin: 72.5,
		lastUpdated: '2024-01-15',
	},
];
