version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: identity-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-identity_db}
    ports:
      - '${POSTGRES_PORT:-5431}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - identity-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres}']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  identity-network:
    driver: bridge

volumes:
  postgres_data:
