import { WorkFlowModel } from '@/dtos/purchase-request.dto';
import {
	ActivityLogEntry,
	Attachment,
	ExtraCost,
	FinancialSummary,
	GoodsReceiveNoteItem,
	GoodsReceiveNoteStatus,
	StockMovement,
	Comment,
	PrType,
	PurchaseRequestItem,
	PurchaseOrder,
	PurchaseOrderStatus,
	DocumentStatus,
	WorkflowStage,
	WorkflowStatus,
} from '@/lib/types';

export interface CreditNote {
	id: string;
	refNumber: string;
	description: string;
	vendorId: string;
	vendorName: string;
	createdDate: Date;
	docNumber: string;
	docDate: Date;
	netAmount: number;
	taxAmount: number;
	totalAmount: number;
	currency: string;
	status: string;
	notes: string;
	createdBy: string;
	updatedDate: Date;
	updatedBy: string;
	items: CreditNoteItem[];
	attachments: CreditNoteAttachment[];
}

export type CreditNoteStatus =
	| 'draft'
	| 'pending'
	| 'approved'
	| 'rejected'
	| 'void';

export type CreditNoteType = CreditNote;

export interface CreditNoteItem {
	id: string;
	description: string;
	quantity: number;
	unitPrice: number;
	discountPercentage: number;
	taxPercentage: number;
}

export interface CreditNoteAttachment {
	id: string;
	fileName: string;
	fileSize: number;
	uploadDate: Date;
	uploadedBy: string;
}

export interface EditedItem {
	id: string;
	productName: string;
	productDescription: string;
	location: string;
	lotNo: string;
	orderUnit: string;
	inventoryUnit: string;
	rcvQty: number;
	cnQty: number;
	unitPrice: number;
	cnAmt: number;
	costVariance: number;
	discountAmount: number;
	totalReceivedQty: number;
	grnNumber: string;
	grnDate: Date;
	taxRate: number;
	tax: number;
	total: number;
	appliedLots?: Array<{
		lotNumber: string;
		receiveDate: Date;
		grnNumber: string;
		invoiceNumber: string;
	}>;
}

export const staticCreditNotes: CreditNoteType[] = [
	{
		id: 'credit-note-1',
		refNumber: 'CN-001',
		description: 'Credit Note for Invoice INV-001',
		vendorName: 'Vendor A',
		status: 'Draft',
		createdDate: new Date('2023-10-01'),
		docNumber: 'DOC-001',
		docDate: new Date('2023-10-01'),
		netAmount: 1000,
		taxAmount: 100,
		totalAmount: 1100,
		vendorId: 'vendor-1',
		currency: 'USD',
		notes: 'This is a test credit note',
		createdBy: 'admin',
		updatedDate: new Date('2023-10-01'),
		updatedBy: 'admin',
		items: [],
		attachments: [],
	},
	{
		id: 'credit-note-2',
		refNumber: 'CN-002',
		description: 'Credit Note for Invoice INV-002',
		vendorName: 'Vendor B',
		status: 'Submitted',
		createdDate: new Date('2023-10-02'),
		docNumber: 'DOC-002',
		docDate: new Date('2023-10-02'),
		netAmount: 2000,
		taxAmount: 200,
		totalAmount: 2200,
		vendorId: 'vendor-2',
		currency: 'USD',
		notes: 'This is a test credit note',
		createdBy: 'admin',
		updatedDate: new Date('2023-10-02'),
		updatedBy: 'admin',
		items: [],
		attachments: [],
	},
	{
		id: 'credit-note-3',
		refNumber: 'CN-003',
		description: 'Credit Note for Invoice INV-003',
		vendorName: 'Vendor C',
		status: 'Approved',
		createdDate: new Date('2023-10-03'),
		docNumber: 'DOC-003',
		docDate: new Date('2023-10-03'),
		netAmount: 1500,
		taxAmount: 150,
		totalAmount: 1650,
		vendorId: 'vendor-3',
		currency: 'USD',
		notes: 'This is a test credit note',
		createdBy: 'admin',
		updatedDate: new Date('2023-10-03'),
		updatedBy: 'admin',
		items: [],
		attachments: [],
	},
	{
		id: 'credit-note-4',
		refNumber: 'CN-004',
		description: 'Credit Note for Invoice INV-004',
		vendorName: 'Vendor D',
		status: 'Rejected',
		createdDate: new Date('2023-10-04'),
		docNumber: 'DOC-004',
		docDate: new Date('2023-10-04'),
		netAmount: 2500,
		taxAmount: 250,
		totalAmount: 2750,
		vendorId: 'vendor-4',
		currency: 'USD',
		notes: 'This is a test credit note',
		createdBy: 'admin',
		updatedDate: new Date('2023-10-04'),
		updatedBy: 'admin',
		items: [],
		attachments: [],
	},
	{
		id: 'credit-note-5',
		refNumber: 'CN-005',
		description: 'Credit Note for Invoice INV-005',
		vendorName: 'Vendor E',
		status: 'Voided',
		createdDate: new Date('2023-10-05'),
		docNumber: 'DOC-005',
		docDate: new Date('2023-10-05'),
		netAmount: 3000,
		taxAmount: 300,
		totalAmount: 3300,
		vendorId: 'vendor-5',
		currency: 'USD',
		notes: 'This is a test credit note',
		createdBy: 'admin',
		updatedDate: new Date('2023-10-05'),
		updatedBy: 'admin',
		items: [],
		attachments: [],
	},
	// Continue adding more entries as needed
];

export interface GoodsReceiveNote {
	id: string;
	ref: string;
	date: Date;
	invoiceDate: Date;
	invoiceNumber: string;
	taxInvoiceDate?: Date;
	taxInvoiceNumber?: string;
	description: string;
	receiver: string;
	vendorId: string;
	vendor: string;
	location: string;
	currency: string;
	exchangeRate: number;
	baseCurrency: string;
	status: GoodsReceiveNoteStatus | string;
	isConsignment: boolean;
	isCash: boolean;
	cashBook?: string;
	items: GoodsReceiveNoteItem[];
	selectedItems: string[];
	stockMovements: StockMovement[];
	extraCosts: ExtraCost[];
	comments: Comment[];
	attachments: Attachment[];
	activityLog: ActivityLogEntry[];
	financialSummary?: FinancialSummary | null;
	baseSubTotalPrice: number;
	subTotalPrice: number;
	baseNetAmount: number;
	netAmount: number;
	baseDiscAmount: number;
	discountAmount: number;
	baseTaxAmount: number;
	taxAmount: number;
	baseTotalAmount: number;
	totalAmount: number;
	creditTerms?: string;
	dueDate?: Date;
}

export const mockGoodsReceiveNotes: GoodsReceiveNote[] = [
	{
		id: 'GRN006',
		ref: 'GRN-2023-006',
		date: new Date('2023-08-10'),
		selectedItems: [],
		invoiceDate: new Date('2023-08-09'),
		invoiceNumber: 'INV-20230809-006',
		taxInvoiceDate: new Date('2023-08-09'),
		taxInvoiceNumber: 'TAX-20230809-006',
		description: 'Kitchen Equipment Delivery',
		receiver: 'Alice Thompson',
		vendor: 'Professional Kitchen Supplies',
		vendorId: 'VENDOR-001',
		location: 'Kitchen Storage',
		currency: 'USD',
		status: 'Received',
		isConsignment: false,
		isCash: false,
		cashBook: 'General Cash Book',
		items: [
			{
				id: 'ITEM011',
				name: 'Commercial Blender',
				description: 'High-power, 3HP motor',
				jobCode: 'JOB-2023-006',
				orderedQuantity: 5,
				receivedQuantity: 5,
				unit: 'piece',
				unitPrice: 399.99,
				totalAmount: 1999.95,
				subTotalAmount: 1999.95,
				currency: 'USD',
				exchangeRate: 1,
				taxRate: 0.08,
				taxAmount: 160,
				discountRate: 0.1,
				discountAmount: 200,
				netAmount: 1959.95,
				baseQuantity: 5,
				baseUnitPrice: 399.99,
				baseUnit: 'piece',
				baseCurrency: 'USD',
				conversionRate: 1,
				baseSubTotalAmount: 1999.95,
				baseNetAmount: 1959.95,
				baseTotalAmount: 1999.95,
				baseTaxRate: 0.08,
				baseTaxAmount: 160,
				baseDiscountRate: 0.1,
				baseDiscountAmount: 200,
				extraCost: 50,
				inventoryOnHand: 5,
				inventoryOnOrder: 0,
				inventoryReorderThreshold: 2,
				inventoryRestockLevel: 1,
				purchaseOrderRef: 'PO-2023-006',
				lastPurchasePrice: 399.99,
				lastOrderDate: new Date('2023-08-10'),
				lastVendor: 'Professional Kitchen Supplies',
				lotNumber: 'LOT-2023-011',
				deliveryPoint: 'Kitchen Receiving',
				deliveryDate: new Date('2023-08-10'),
				location: 'Kitchen Storage',
				isFreeOfCharge: false,
				taxIncluded: false,
				adjustments: {
					discount: false,
					tax: false,
				},
			},
			{
				id: 'ITEM012',
				name: "Chef's Knives Set",
				description: 'Professional 8-piece set',
				jobCode: 'JOB-2023-006',
				orderedQuantity: 10,
				receivedQuantity: 10,
				unit: 'set',
				unitPrice: 249.99,
				totalAmount: 2499.9,
				subTotalAmount: 2499.9,
				currency: 'USD',
				exchangeRate: 1,
				taxRate: 0.08,
				taxAmount: 200,
				discountRate: 0.05,
				discountAmount: 125,
				netAmount: 2574.9,
				baseQuantity: 10,
				baseUnitPrice: 249.99,
				baseUnit: 'set',
				baseCurrency: 'USD',
				conversionRate: 1,
				baseSubTotalAmount: 2499.9,
				baseNetAmount: 2574.9,
				baseTotalAmount: 2499.9,
				baseTaxRate: 0.08,
				baseTaxAmount: 200,
				baseDiscountRate: 0.05,
				baseDiscountAmount: 125,
				extraCost: 25,
				inventoryOnHand: 10,
				inventoryOnOrder: 0,
				inventoryReorderThreshold: 3,
				inventoryRestockLevel: 2,
				purchaseOrderRef: 'PO-2023-006',
				lastPurchasePrice: 249.99,
				lastOrderDate: new Date('2023-08-10'),
				lastVendor: 'Professional Kitchen Supplies',
				lotNumber: 'LOT-2023-012',
				deliveryPoint: 'Kitchen Receiving',
				deliveryDate: new Date('2023-08-10'),
				location: 'Kitchen Storage',
				isFreeOfCharge: false,
				taxIncluded: false,
				adjustments: {
					discount: false,
					tax: false,
				},
			},
		],
		stockMovements: [
			{
				id: '3',
				itemName: 'Commercial Blender',
				quantity: 5,
				unit: 'piece',
				fromLocation: 'Kitchen Receiving',
				toLocation: 'Kitchen Storage',
				netAmount: 1249.95,
				extraCost: 50,
				totalAmount: 1299.95,
				cost: 249.99,
				totalCost: 1249.95,
				currency: 'USD',
				itemDescription: '',
				lotNumber: 1,
			},
			{
				id: '4',
				itemName: "Chef's Knives Set",
				quantity: 10,
				unit: 'set',
				fromLocation: 'Kitchen Receiving',
				toLocation: 'Kitchen Storage',
				netAmount: 2499.9,
				extraCost: 25,
				totalAmount: 2524.9,
				cost: 249.99,
				totalCost: 1249.95,
				currency: 'USD',
				itemDescription: '',
				lotNumber: 1,
			},
		],
		extraCosts: [
			{
				id: 'EC002',
				type: 'handling',
				amount: 75,
				currency: 'USD',
				exchangeRate: 1,
				baseAmount: 75,
				baseCurrency: 'USD',
			},
		],
		comments: [
			{
				id: 'COM002',
				text: 'All kitchen equipment received in excellent condition.',
				content: 'All kitchen equipment received in excellent condition.',
				timestamp: new Date('2023-08-10T14:45:00Z'),
				userName: 'Alice Thompson',
				userId: '102',
			},
		],
		attachments: [
			{
				id: 'ATT002',
				publicAccess: true,
				userId: '102',
				userName: 'Alice Thompson',
				fileName: 'Kitchen_Equipment_Invoice.pdf',
				fileType: 'application/pdf',
				fileSize: 2048,
				fileUrl: 'https://example.com/Kitchen_Equipment_Invoice.pdf',
				uploadDate: new Date('2023-08-10T15:00:00Z'),
			},
		],
		activityLog: [
			{
				id: 'LOG003',
				action: 'Created Goods Receive Note',
				userId: '102',
				userName: 'Alice Thompson',
				activityType: 'Document',
				description: 'Goods Receive Note created for kitchen equipment',
				timestamp: new Date('2023-08-10T14:30:00Z'),
			},
			{
				id: 'LOG004',
				action: 'Marked as Received',
				userId: '102',
				userName: 'Alice Thompson',
				activityType: 'Document',
				description: 'Kitchen equipment marked as received',
				timestamp: new Date('2023-08-10T15:15:00Z'),
			},
		],
		financialSummary: {
			id: 'FS002',
			netAmount: 4499.85,
			taxAmount: 360,
			totalAmount: 4859.85,
			currency: 'USD',
			baseNetAmount: 4499.85,
			baseTaxAmount: 360,
			baseTotalAmount: 4859.85,
			baseCurrency: 'USD',
			jvType: 'GRN',
			jvNumber: 'JV-2023-002',
			jvDate: new Date('2023-08-10'),
			jvDescription: 'Goods Receive Note - Kitchen Equipment',
			jvStatus: 'posted',
			jvReference: 'GRN-2023-006',
			jvDetail: [
				{
					department: { id: 'DEPT-001', name: 'Purchasing' },
					accountCode: { id: 'ACC-001', code: '1000', name: 'Inventory' },
					accountName: 'Inventory',
					currency: 'USD',
					debit: 4499.85,
					credit: 0,
					baseCurrency: 'USD',
					baseDebit: 4499.85,
					baseCredit: 0,
				},
				{
					department: { id: 'DEPT-002', name: 'Finance' },
					accountCode: {
						id: 'ACC-002',
						code: '2000',
						name: 'Accounts Payable',
					},
					accountName: 'Accounts Payable',
					currency: 'USD',
					debit: 0,
					credit: 4499.85,
					baseCurrency: 'USD',
					baseDebit: 0,
					baseCredit: 4499.85,
				},
				{
					department: { id: 'DEPT-002', name: 'Finance' },
					accountCode: { id: 'ACC-003', code: '2200', name: 'VAT Payable' },
					accountName: 'VAT Payable',
					currency: 'USD',
					debit: 0,
					credit: 360,
					baseCurrency: 'USD',
					baseDebit: 0,
					baseCredit: 360,
				},
				{
					department: { id: 'DEPT-003', name: 'Warehouse' },
					accountCode: { id: 'ACC-004', code: '5000', name: 'Freight In' },
					accountName: 'Freight In',
					currency: 'USD',
					debit: 360,
					credit: 0,
					baseCurrency: 'USD',
					baseDebit: 360,
					baseCredit: 0,
				},
			],
			jvTotal: {
				debit: 4859.85,
				credit: 4859.85,
				baseDebit: 4859.85,
				baseCredit: 4859.85,
				baseCurrency: 'USD',
			},
		},

		exchangeRate: 1,
		baseCurrency: 'USD',
		baseSubTotalPrice: 4499.85,
		subTotalPrice: 4499.85,
		baseNetAmount: 4499.85,
		netAmount: 4499.85,
		baseDiscAmount: 325,
		discountAmount: 325,
		baseTaxAmount: 360,
		taxAmount: 360,
		baseTotalAmount: 4859.85,
		totalAmount: 4859.85,
	},
	{
		id: 'GRN007',
		ref: 'GRN-2023-007',
		date: new Date('2023-08-15'),
		selectedItems: [],
		invoiceDate: new Date('2023-08-14'),
		invoiceNumber: 'INV-20230814-007',
		taxInvoiceDate: new Date('2023-08-14'),
		taxInvoiceNumber: 'TAX-20230814-007',
		description: 'Office Furniture Delivery',
		receiver: 'Bob Johnson',
		vendorId: 'VENDOR-001',
		vendor: 'Modern Office Solutions',
		location: 'Office Storage',
		currency: 'USD',
		status: 'Pending',
		isConsignment: false,
		isCash: true,
		cashBook: 'Petty Cash',
		items: [
			{
				id: 'ITEM013',
				name: 'Ergonomic Office Chair',
				description: 'Adjustable height and lumbar support',
				jobCode: 'JOB-2023-007',
				orderedQuantity: 20,
				receivedQuantity: 20,
				unit: 'piece',
				unitPrice: 199.99,
				totalAmount: 3999.8,
				subTotalAmount: 3999.8,
				currency: 'USD',
				exchangeRate: 1,
				taxRate: 0.08,
				taxAmount: 320,
				discountRate: 0.05,
				discountAmount: 200,
				netAmount: 4119.8,
				baseQuantity: 20,
				baseUnitPrice: 199.99,
				baseUnit: 'piece',
				baseCurrency: 'USD',
				conversionRate: 1,
				baseSubTotalAmount: 3999.8,
				baseNetAmount: 3999.8,
				baseTotalAmount: 3999.8,
				baseTaxRate: 0.08,
				baseTaxAmount: 320,
				baseDiscountRate: 0.05,
				baseDiscountAmount: 200,
				extraCost: 100,
				inventoryOnHand: 20,
				inventoryOnOrder: 0,
				inventoryReorderThreshold: 5,
				inventoryRestockLevel: 10,
				purchaseOrderRef: 'PO-2023-007',
				lastPurchasePrice: 199.99,
				lastOrderDate: new Date('2023-08-15'),
				lastVendor: 'Modern Office Solutions',
				lotNumber: 'LOT-2023-013',
				deliveryPoint: 'Office Receiving',
				deliveryDate: new Date('2023-08-15'),
				location: 'Office Storage',
				isFreeOfCharge: false,
				taxIncluded: false,
				adjustments: {
					discount: false,
					tax: false,
				},
			},
		],
		stockMovements: [
			{
				id: '5',
				itemName: 'Ergonomic Office Chair',
				unit: 'piece',
				quantity: 20,
				fromLocation: 'Office Receiving',
				toLocation: 'Office Storage',
				netAmount: 3999.8,
				extraCost: 100,
				totalAmount: 4099.8,
				cost: 199.99,
				totalCost: 3999.8,
				currency: 'USD',
				itemDescription: '',
				lotNumber: 1,
			},
		],
		extraCosts: [
			{
				id: 'EC003',
				type: 'handling',
				amount: 100,
				currency: 'USD',
				exchangeRate: 1,
				baseAmount: 100,
				baseCurrency: 'USD',
			},
		],
		comments: [
			{
				id: 'COM003',
				text: 'Chairs arrived, pending assembly and inspection.',
				content: 'Chairs arrived, pending assembly and inspection.',
				timestamp: new Date('2023-08-15T10:30:00Z'),
				userName: 'Bob Johnson',
				userId: '103',
			},
		],
		attachments: [
			{
				id: 'ATT003',
				publicAccess: true,
				userId: '103',
				userName: 'Bob Johnson',
				fileName: 'Office_Chairs_Delivery_Note.pdf',
				fileType: 'application/pdf',
				fileSize: 1024,
				fileUrl: 'https://example.com/Office_Chairs_Delivery_Note.pdf',
				uploadDate: new Date('2023-08-15T11:00:00Z'),
			},
		],
		activityLog: [
			{
				id: 'LOG005',
				action: 'Created Goods Receive Note',
				userId: '103',
				userName: 'Bob Johnson',
				activityType: 'Document',
				description: 'Goods Receive Note created for office chairs',
				timestamp: new Date('2023-08-15T10:15:00Z'),
			},
		],
		exchangeRate: 1,
		baseCurrency: 'USD',
		baseSubTotalPrice: 3999.8,
		subTotalPrice: 3999.8,
		baseNetAmount: 3999.8,
		netAmount: 3999.8,
		baseDiscAmount: 200,
		discountAmount: 200,
		baseTaxAmount: 320,
		taxAmount: 320,
		baseTotalAmount: 4319.8,
		totalAmount: 4319.8,
	},
	{
		id: 'GRN009',
		ref: 'GRN-2023-007',
		date: new Date('2023-08-15'),
		selectedItems: [],
		invoiceDate: new Date('2023-08-14'),
		invoiceNumber: 'INV-20230814-007',
		taxInvoiceDate: new Date('2023-08-14'),
		taxInvoiceNumber: 'TAX-20230814-007',
		description: 'Office Furniture Delivery',
		receiver: 'Bob Johnson',
		vendorId: 'VENDOR-005',
		vendor: 'Modern Office Solutions',
		location: 'Office Storage',
		currency: 'USD',
		status: 'Cancelled',
		isConsignment: false,
		isCash: true,
		cashBook: 'Petty Cash',
		items: [
			{
				id: 'ITEM013',
				name: 'Ergonomic Office Chair',
				description: 'Adjustable height and lumbar support',
				jobCode: 'JOB-2023-007',
				orderedQuantity: 20,
				receivedQuantity: 20,
				unit: 'piece',
				unitPrice: 199.99,
				totalAmount: 3999.8,
				subTotalAmount: 3999.8,
				currency: 'USD',
				exchangeRate: 1,
				taxRate: 0.08,
				taxAmount: 320,
				discountRate: 0.05,
				discountAmount: 200,
				netAmount: 4119.8,
				baseQuantity: 20,
				baseUnitPrice: 199.99,
				baseUnit: 'piece',
				baseCurrency: 'USD',
				conversionRate: 1,
				baseSubTotalAmount: 3999.8,
				baseNetAmount: 3999.8,
				baseTotalAmount: 3999.8,
				baseTaxRate: 0.08,
				baseTaxAmount: 320,
				baseDiscountRate: 0.05,
				baseDiscountAmount: 200,
				extraCost: 100,
				inventoryOnHand: 20,
				inventoryOnOrder: 0,
				inventoryReorderThreshold: 5,
				inventoryRestockLevel: 10,
				purchaseOrderRef: 'PO-2023-007',
				lastPurchasePrice: 199.99,
				lastOrderDate: new Date('2023-08-15'),
				lastVendor: 'Modern Office Solutions',
				lotNumber: 'LOT-2023-013',
				deliveryPoint: 'Office Receiving',
				deliveryDate: new Date('2023-08-15'),
				location: 'Office Storage',
				isFreeOfCharge: false,
				taxIncluded: false,
				adjustments: {
					discount: false,
					tax: false,
				},
			},
		],
		stockMovements: [
			{
				id: '5',
				itemName: 'Ergonomic Office Chair',
				unit: 'piece',
				quantity: 20,
				fromLocation: 'Office Receiving',
				toLocation: 'Office Storage',
				netAmount: 3999.8,
				extraCost: 100,
				totalAmount: 4099.8,
				cost: 199.99,
				totalCost: 3999.8,
				currency: 'USD',
				itemDescription: '',
				lotNumber: 1,
			},
		],
		extraCosts: [
			{
				id: 'EC003',
				type: 'handling',
				amount: 100,
				currency: 'USD',
				exchangeRate: 1,
				baseAmount: 100,
				baseCurrency: 'USD',
			},
		],
		comments: [
			{
				id: 'COM003',
				text: 'Chairs arrived, pending assembly and inspection.',
				content: 'Chairs arrived, pending assembly and inspection.',
				timestamp: new Date('2023-08-15T10:30:00Z'),
				userName: 'Bob Johnson',
				userId: '103',
			},
		],
		attachments: [
			{
				id: 'ATT003',
				publicAccess: true,
				userId: '103',
				userName: 'Bob Johnson',
				fileName: 'Office_Chairs_Delivery_Note.pdf',
				fileType: 'application/pdf',
				fileSize: 1024,
				fileUrl: 'https://example.com/Office_Chairs_Delivery_Note.pdf',
				uploadDate: new Date('2023-08-15T11:00:00Z'),
			},
		],
		activityLog: [
			{
				id: 'LOG005',
				action: 'Created Goods Receive Note',
				userId: '103',
				userName: 'Bob Johnson',
				activityType: 'Document',
				description: 'Goods Receive Note created for office chairs',
				timestamp: new Date('2023-08-15T10:15:00Z'),
			},
		],
		exchangeRate: 1,
		baseCurrency: 'USD',
		baseSubTotalPrice: 3999.8,
		subTotalPrice: 3999.8,
		baseNetAmount: 3999.8,
		netAmount: 3999.8,
		baseDiscAmount: 200,
		discountAmount: 200,
		baseTaxAmount: 320,
		taxAmount: 320,
		baseTotalAmount: 4319.8,
		totalAmount: 4319.8,
	},
];

export const prData: PrType[] = [
	{
		id: 'PR-001',
		type: 'General Purchase',
		description: 'Office Supplies',
		requestor: 'John Doe',
		department: 'Administration',
		date: new Date('2023-06-15'),
		status: 'Submitted',
		amount: 500,
		currentStage: 'Initial Review',
	},
	{
		id: 'PR-002',
		type: 'Market List',
		description: 'Weekly Groceries',
		requestor: 'Jane Smith',
		department: 'Catering',
		date: new Date('2023-06-14'),
		status: 'Approved',
		amount: 750,
		currentStage: 'Procurement',
	},
	{
		id: 'PR-003',
		type: 'Asset Purchase',
		description: 'Laptop Computers',
		requestor: 'Mike Johnson',
		department: 'IT',
		date: new Date('2023-06-13'),
		status: 'Rejected',
		amount: 3000,
		currentStage: 'Final Review',
	},
	{
		id: 'PR-004',
		type: 'General Purchase',
		description: 'Office Furniture',
		requestor: 'Emily Brown',
		department: 'HR',
		date: new Date('2023-06-12'),
		status: 'Draft',
		amount: 1200,
		currentStage: 'Draft',
	},
	{
		id: 'PR-005',
		type: 'Market List',
		description: 'Monthly Supplies',
		requestor: 'David Lee',
		department: 'Facilities',
		date: new Date('2023-06-11'),
		status: 'Submitted',
		amount: 900,
		currentStage: 'Department Approval',
	},
	{
		id: 'PR-006',
		type: 'Asset Purchase',
		description: 'Server Equipment',
		requestor: 'Sarah Connor',
		department: 'IT',
		date: new Date('2023-06-10'),
		status: 'Approved',
		amount: 5000,
		currentStage: 'Procurement',
	},
	{
		id: 'PR-007',
		type: 'General Purchase',
		description: 'Marketing Materials',
		requestor: 'Tom Wilson',
		department: 'Marketing',
		date: new Date('2023-06-09'),
		status: 'Submitted',
		amount: 800,
		currentStage: 'Financial Review',
	},
	{
		id: 'PR-008',
		type: 'Market List',
		description: 'Event Catering',
		requestor: 'Alice Johnson',
		department: 'Events',
		date: new Date('2023-06-08'),
		status: 'Approved',
		amount: 1500,
		currentStage: 'Procurement',
	},
	{
		id: 'PR-009',
		type: 'Asset Purchase',
		description: 'Company Vehicles',
		requestor: 'Robert Davis',
		department: 'Operations',
		date: new Date('2023-06-07'),
		status: 'Rejected',
		amount: 50000,
		currentStage: 'Final Review',
	},
	{
		id: 'PR-010',
		type: 'General Purchase',
		description: 'Training Materials',
		requestor: 'Emma White',
		department: 'HR',
		date: new Date('2023-06-06'),
		status: 'Draft',
		amount: 300,
		currentStage: 'Draft',
	},
];

const prDataTransaction = {
	baseCurrencyCode: 'THB',
	currency: 'USD',
	baseSubTotalPrice: 1000,
	subTotalPrice: 28.57,
	baseDiscAmount: 100,
	discountAmount: 2.86,
	baseNetAmount: 900,
	netAmount: 25.71,
	baseTaxAmount: 63,
	taxAmount: 1.8,
	baseTotalAmount: 963,
	totalAmount: 27.51,
};

export const dataTransaction = [
	{
		Label: 'Subtotal Amount',
		localCurrency: prDataTransaction.baseCurrencyCode ?? 'THB',
		localAmt: prDataTransaction.baseSubTotalPrice ?? 0,
		currentCurrency: prDataTransaction.currency ?? 'THB',
		currentAmt: prDataTransaction.subTotalPrice ?? 0,
	},
	{
		Label: 'Discount Amount',
		localCurrency: prDataTransaction.baseCurrencyCode ?? 'THB',
		localAmt: prDataTransaction.baseDiscAmount ?? 0,
		currentCurrency: prDataTransaction.currency ?? 'THB',
		currentAmt: prDataTransaction.discountAmount ?? 0,
	},
	{
		Label: 'Net Amount',
		localCurrency: prDataTransaction.baseCurrencyCode ?? 'THB',
		localAmt: prDataTransaction.baseNetAmount ?? 0,
		currentCurrency: prDataTransaction.currency ?? 'THB',
		currentAmt: prDataTransaction.netAmount ?? 0,
	},
	{
		Label: 'Tax Amount',
		localCurrency: prDataTransaction.baseCurrencyCode ?? 'THB',
		localAmt: prDataTransaction.baseTaxAmount ?? 0,
		currentCurrency: prDataTransaction.currency ?? 'THB',
		currentAmt: prDataTransaction.taxAmount ?? 0,
	},
	{
		Label: 'Total Amount',
		localCurrency: prDataTransaction.baseCurrencyCode ?? 'THB',
		localAmt: prDataTransaction.baseTotalAmount ?? 0,
		currentCurrency: prDataTransaction.currency ?? 'THB',
		currentAmt: prDataTransaction.totalAmount ?? 0,
	},
];

export const itemDetails: PurchaseRequestItem[] = [
	{
		id: '1',
		location: 'Warehouse A',
		name: 'Office Chair',
		description: 'Ergonomic office chair with lumbar support',
		unit: 'Piece',
		quantityRequested: 10,
		quantityApproved: 8,
		inventoryInfo: {
			onHand: 5,
			onOrdered: 15,
			lastPrice: 199.99,
			lastOrderDate: new Date('2023-05-15'),
			lastVendor: 'Office Supplies Co.',
			reorderLevel: 10,
			restockLevel: 20,
			averageMonthlyUsage: 7,
			inventoryUnit: 'Piece',
		},
		currency: 'USD',
		price: 199.99,
		totalAmount: 1599.92,
		status: 'Accepted',
		taxRate: 0.08,
		taxAmount: 127.99,
		discountRate: 0.05,
		discountAmount: 79.99,
		netAmount: 1647.92,
		deliveryDate: new Date('2023-07-01'),
		deliveryPoint: 'Main Office',
		jobCode: 'OFF-2023',
		createdDate: new Date('2023-06-01'),
		updatedDate: new Date('2023-06-10'),
		createdBy: 'John Doe',
		updatedBy: 'Jane Smith',
		itemCategory: 'Furniture',
		itemSubcategory: 'Seating',
		vendor: 'Office Supplies Co.',
		pricelistNumber: 'PL-2023-06',
		comment: 'Urgent requirement for new hires',
		adjustments: {
			discount: false,
			tax: false,
		},
		taxIncluded: false,
		currencyRate: 1,
		foc: 0,
		accountCode: 'FURN-1001',
		baseSubTotalPrice: 1999.9,
		subTotalPrice: 1999.9,
		baseNetAmount: 1647.92,
		baseDiscAmount: 79.99,
		baseTaxAmount: 127.99,
		baseTotalAmount: 1599.92,
	},
	{
		id: '2',
		location: 'Warehouse B',
		name: 'Laptop',
		description: 'High-performance laptop for developers',
		unit: 'Piece',
		quantityRequested: 5,
		quantityApproved: 4,
		inventoryInfo: {
			onHand: 2,
			onOrdered: 10,
			lastPrice: 1299.99,
			lastOrderDate: new Date('2023-04-20'),
			lastVendor: 'Tech Solutions Inc.',
			reorderLevel: 5,
			restockLevel: 15,
			averageMonthlyUsage: 3,
			inventoryUnit: 'Piece',
		},
		currency: 'USD',
		price: 1299.99,
		totalAmount: 5199.96,
		status: 'Review',
		taxRate: 0.08,
		taxAmount: 415.99,
		discountRate: 0.1,
		discountAmount: 519.99,
		netAmount: 5095.96,
		deliveryDate: new Date('2023-07-15'),
		deliveryPoint: 'IT Department',
		jobCode: 'IT-2023',
		createdDate: new Date('2023-06-05'),
		updatedDate: new Date('2023-06-12'),
		createdBy: 'Alice Johnson',
		updatedBy: 'Bob Williams',
		itemCategory: 'Electronics',
		itemSubcategory: 'Computers',
		vendor: 'Tech Solutions Inc.',
		pricelistNumber: 'PL-2023-06-TECH',
		comment: 'Needed for new development team',
		adjustments: {
			discount: false,
			tax: true,
		},
		taxIncluded: true,
		currencyRate: 1,
		foc: 0,
		accountCode: 'TECH-2001',
		baseSubTotalPrice: 5199.96,
		subTotalPrice: 5199.96,
		baseNetAmount: 5095.96,
		baseDiscAmount: 519.99,
		baseTaxAmount: 415.99,
		baseTotalAmount: 5199.96,
	},
	{
		id: '3',
		location: 'Warehouse C',
		name: 'Printer',
		description: 'High-speed color laser printer',
		unit: 'Piece',
		quantityRequested: 2,
		quantityApproved: 2,
		inventoryInfo: {
			onHand: 1,
			onOrdered: 3,
			lastPrice: 599.99,
			lastOrderDate: new Date('2023-05-01'),
			lastVendor: 'Office Tech Ltd.',
			reorderLevel: 2,
			restockLevel: 5,
			averageMonthlyUsage: 1,
			inventoryUnit: 'Piece',
		},
		currency: 'USD',
		price: 599.99,
		totalAmount: 1199.98,
		status: 'Accepted',
		taxRate: 0.08,
		taxAmount: 95.99,
		discountRate: 0,
		discountAmount: 0,
		netAmount: 1295.97,
		deliveryDate: new Date('2023-07-10'),
		deliveryPoint: 'Admin Office',
		jobCode: 'ADMIN-2023',
		createdDate: new Date('2023-06-07'),
		updatedDate: new Date('2023-06-14'),
		createdBy: 'Emma Davis',
		updatedBy: 'Michael Brown',
		itemCategory: 'Electronics',
		itemSubcategory: 'Printers',
		vendor: 'Office Tech Ltd.',
		pricelistNumber: 'PL-2023-06-OT',
		comment: 'Replacement for old printer',
		currencyRate: 1,
		foc: 0,
		accountCode: 'TECH-3001',
		baseSubTotalPrice: 1199.98,
		subTotalPrice: 1199.98,
		baseNetAmount: 1295.97,
		baseDiscAmount: 0,
		baseTaxAmount: 95.99,
		baseTotalAmount: 1199.98,
		adjustments: {
			discount: true,
			tax: true,
		},
		taxIncluded: true,
	},
];

export const budgetData = [
	{
		id: 'budget-001',
		location: 'Front Office',
		category: 'Computer',
		totalBudget: 20000.0,
		softCommitmentDeptHead: 1000.0,
		softCommitmentPO: 3000.0,
		hardCommitment: 2000.0,
		availableBudget: 14000.0,
		currentPRAmount: 15000.0,
	},
	{
		id: 'budget-002',
		location: 'Accounting',
		category: 'Computer',
		totalBudget: 20000.0,
		softCommitmentDeptHead: 0.0,
		softCommitmentPO: 0.0,
		hardCommitment: 0.0,
		availableBudget: 20000.0,
		currentPRAmount: 13000.0,
	},
	{
		id: 'budget-003',
		location: 'HouseKeeping',
		category: 'Computer',
		totalBudget: 20000.0,
		softCommitmentDeptHead: 0.0,
		softCommitmentPO: 0.0,
		hardCommitment: 0.0,
		availableBudget: 20000.0,
		currentPRAmount: 10000.0,
	},
];

export const workFlowData: WorkFlowModel[] = [
	{
		id: 'wf-001',
		stage: 'Department Head Approval',
		approver: 'Jane Smith',
		status: 'Approved',
		date: '2023-07-16',
		comments: 'Approved as per department policy',
	},
	{
		id: 'wf-002',
		stage: 'Finance Manager Approval',
		approver: 'Mike Johnson',
		status: 'Pending',
		date: null,
		comments: null,
	},
	{
		id: 'wf-003',
		stage: 'CEO Approval',
		approver: 'Sarah Lee',
		status: 'Approved',
		date: '2023-07-18',
		comments: 'Final approval granted',
	},
	{
		id: 'wf-004',
		stage: 'HR Review',
		approver: 'David Brown',
		status: 'Rejected',
		date: '2023-07-19',
		comments: 'Missing required documents',
	},
	{
		id: 'wf-005',
		stage: 'IT Security Check',
		approver: 'Emma Wilson',
		status: 'Approved',
		date: '2023-07-20',
		comments: 'No security concerns found',
	},
	{
		id: 'wf-006',
		stage: 'Compliance Review',
		approver: 'Liam Carter',
		status: 'Pending',
		date: null,
		comments: null,
	},
	{
		id: 'wf-007',
		stage: 'Operations Approval',
		approver: 'Sophia Green',
		status: 'Approved',
		date: '2023-07-22',
		comments: 'Reviewed and approved',
	},
	{
		id: 'wf-008',
		stage: 'Procurement Approval',
		approver: 'James White',
		status: 'Rejected',
		date: '2023-07-23',
		comments: 'Budget exceeded',
	},
	{
		id: 'wf-009',
		stage: 'Legal Review',
		approver: 'Olivia Harris',
		status: 'In Review',
		date: null,
		comments: 'Under legal consideration',
	},
	{
		id: 'wf-010',
		stage: 'Board Approval',
		approver: 'Daniel Martinez',
		status: 'On Hold',
		date: '2023-07-25',
		comments: 'Further discussion required',
	},
];

export const Mock_purchaseOrders: PurchaseOrder[] = [
	{
		poId: 'PO-002',
		number: 'PO-2023-002',
		vendorId: 2,
		vendorName: 'Office Supplies Inc.',
		orderDate: new Date('2023-06-05'),
		DeliveryDate: new Date('2023-06-20'),
		status: PurchaseOrderStatus.Sent,
		totalAmount: 770.0,
		currencyCode: 'USD',
		baseCurrencyCode: 'USD',
		exchangeRate: 1,
		notes: 'Monthly office supply order',
		createdBy: 102,
		approvedBy: 203,
		approvalDate: new Date('2023-06-06'),
		email: 'orders@officesupplies.com',
		buyer: 'Jane Doe',
		creditTerms: 'Net 45',
		description: 'General office supplies',
		remarks: 'Please deliver to reception',
		items: [
			{
				id: 'POI-003',
				name: 'Copy Paper',
				description: 'A4, 80gsm, 500 sheets per ream',
				convRate: 1,
				orderedQuantity: 100,
				orderUnit: 'reams',
				baseQuantity: 100,
				baseUnit: 'reams',
				baseReceivingQty: 0,
				receivedQuantity: 0,
				remainingQuantity: 100,
				unitPrice: 5.0,
				subTotalPrice: 500.0,
				baseSubTotalPrice: 500.0,
				status: 'Pending',
				isFOC: false,
				taxIncluded: false,
				taxRate: 0.1,
				taxAmount: 50.0,
				baseTaxAmount: 50.0,
				discountRate: 0,
				discountAmount: 0,
				baseDiscAmount: 0,
				netAmount: 550.0,
				baseNetAmount: 550.0,
				totalAmount: 550.0,
				baseTotalAmount: 550.0,
				inventoryInfo: {
					onHand: 50,
					onOrdered: 100,
					reorderLevel: 30,
					restockLevel: 80,
					averageMonthlyUsage: 75,
					lastPrice: 4.8,
					lastOrderDate: new Date('2023-05-15'),
					lastVendor: 'Office Supplies Inc.',
				},
			},
			{
				id: 'POI-004',
				name: 'Ballpoint Pens',
				description: 'Blue ink, box of 50',
				convRate: 1,
				orderedQuantity: 20,
				orderUnit: 'boxes',
				baseQuantity: 20,
				baseUnit: 'boxes',
				baseReceivingQty: 0,
				receivedQuantity: 0,
				remainingQuantity: 20,
				unitPrice: 10.0,
				subTotalPrice: 200.0,
				baseSubTotalPrice: 200.0,
				status: 'Pending',
				isFOC: false,
				taxIncluded: false,
				taxRate: 0.1,
				taxAmount: 20.0,
				baseTaxAmount: 20.0,
				discountRate: 0,
				discountAmount: 0,
				baseDiscAmount: 0,
				netAmount: 220.0,
				baseNetAmount: 220.0,
				totalAmount: 220.0,
				baseTotalAmount: 220.0,
				inventoryInfo: {
					onHand: 15,
					onOrdered: 20,
					reorderLevel: 10,
					restockLevel: 25,
					averageMonthlyUsage: 18,
					lastPrice: 9.5,
					lastOrderDate: new Date('2023-05-20'),
					lastVendor: 'Office Supplies Inc.',
				},
			},
		],
		baseSubTotalPrice: 700.0,
		subTotalPrice: 700.0,
		baseNetAmount: 770.0,
		netAmount: 770.0,
		baseDiscAmount: 0,
		discountAmount: 0,
		baseTaxAmount: 70.0,
		taxAmount: 70.0,
		baseTotalAmount: 770.0,
	},
	{
		poId: 'PO-003',
		number: 'PO-2023-003',
		vendorId: 3,
		vendorName: 'Tech Innovations Inc.',
		orderDate: new Date('2023-06-10'),
		DeliveryDate: new Date('2023-07-01'),
		status: PurchaseOrderStatus.Open,
		totalAmount: 16650.0,
		currencyCode: 'USD',
		baseCurrencyCode: 'USD',
		exchangeRate: 1,
		notes: 'IT equipment upgrade',
		createdBy: 103,
		approvedBy: 204,
		approvalDate: new Date('2023-06-11'),
		email: 'sales@techinnovations.com',
		buyer: 'Michael Lee',
		creditTerms: 'Net 60',
		description: 'New laptops and accessories',
		remarks: 'Please schedule installation',
		items: [
			{
				id: 'POI-005',
				name: 'High-Performance Laptop',
				description: '15" display, 32GB RAM, 1TB SSD',
				convRate: 1,
				orderedQuantity: 10,
				orderUnit: 'units',
				baseQuantity: 10,
				baseUnit: 'units',
				baseReceivingQty: 0,
				receivedQuantity: 0,
				remainingQuantity: 10,
				unitPrice: 1500.0,
				subTotalPrice: 15000.0,
				baseSubTotalPrice: 15000.0,
				status: 'Pending',
				isFOC: false,
				taxIncluded: false,
				taxRate: 0.08,
				taxAmount: 1200.0,
				baseTaxAmount: 1200.0,
				discountRate: 0.05,
				discountAmount: 750.0,
				baseDiscAmount: 750.0,
				netAmount: 15450.0,
				baseNetAmount: 15450.0,
				totalAmount: 16650.0,
				baseTotalAmount: 16650.0,
				inventoryInfo: {
					onHand: 5,
					onOrdered: 10,
					reorderLevel: 3,
					restockLevel: 8,
					averageMonthlyUsage: 4,
					lastPrice: 1450.0,
					lastOrderDate: new Date('2023-04-15'),
					lastVendor: 'Tech Innovations Inc.',
				},
			},
		],
		baseSubTotalPrice: 15000.0,
		subTotalPrice: 15000.0,
		baseNetAmount: 15450.0,
		netAmount: 15450.0,
		baseDiscAmount: 750.0,
		discountAmount: 750.0,
		baseTaxAmount: 1200.0,
		taxAmount: 1200.0,
		baseTotalAmount: 16650.0,
	},
	{
		poId: 'PO-004',
		number: 'PO-2023-004',
		vendorId: 4,
		vendorName: 'Fresh Produce Co.',
		orderDate: new Date('2023-06-15'),
		DeliveryDate: new Date('2023-06-17'),
		status: PurchaseOrderStatus.Open,
		totalAmount: 820.0,
		currencyCode: 'USD',
		baseCurrencyCode: 'USD',
		exchangeRate: 1,
		notes: 'Weekly produce order',
		createdBy: 104,
		approvedBy: 205,
		approvalDate: new Date('2023-06-15'),
		email: 'orders@freshproduce.com',
		buyer: 'Sarah Johnson',
		creditTerms: 'Net 7',
		description: 'Fresh fruits and vegetables',
		remarks: 'Early morning delivery preferred',
		items: [
			{
				id: 'POI-006',
				name: 'Organic Apples',
				description: 'Red Delicious, 5lb bag',
				convRate: 1,
				orderedQuantity: 50,
				orderUnit: 'bags',
				baseQuantity: 50,
				baseUnit: 'bags',
				baseReceivingQty: 0,
				receivedQuantity: 0,
				remainingQuantity: 50,
				unitPrice: 10.0,
				subTotalPrice: 500.0,
				baseSubTotalPrice: 500.0,
				status: 'Pending',
				isFOC: false,
				taxIncluded: false,
				taxRate: 0,
				taxAmount: 0,
				baseTaxAmount: 0,
				discountRate: 0,
				discountAmount: 0,
				baseDiscAmount: 0,
				netAmount: 500.0,
				baseNetAmount: 500.0,
				totalAmount: 500.0,
				baseTotalAmount: 500.0,
				inventoryInfo: {
					onHand: 20,
					onOrdered: 50,
					reorderLevel: 15,
					restockLevel: 40,
					averageMonthlyUsage: 180,
					lastPrice: 9.5,
					lastOrderDate: new Date('2023-06-08'),
					lastVendor: 'Fresh Produce Co.',
				},
			},
			{
				id: 'POI-007',
				name: 'Organic Bananas',
				description: '5lb bunch',
				convRate: 1,
				orderedQuantity: 40,
				orderUnit: 'bunches',
				baseQuantity: 40,
				baseUnit: 'bunches',
				baseReceivingQty: 0,
				receivedQuantity: 0,
				remainingQuantity: 40,
				unitPrice: 8.0,
				subTotalPrice: 320.0,
				baseSubTotalPrice: 320.0,
				status: 'Pending',
				isFOC: false,
				taxIncluded: false,
				taxRate: 0,
				taxAmount: 0,
				baseTaxAmount: 0,
				discountRate: 0,
				discountAmount: 0,
				baseDiscAmount: 0,
				netAmount: 320.0,
				baseNetAmount: 320.0,
				totalAmount: 320.0,
				baseTotalAmount: 320.0,
				inventoryInfo: {
					onHand: 15,
					onOrdered: 40,
					reorderLevel: 10,
					restockLevel: 35,
					averageMonthlyUsage: 150,
					lastPrice: 7.8,
					lastOrderDate: new Date('2023-06-08'),
					lastVendor: 'Fresh Produce Co.',
				},
			},
		],
		baseSubTotalPrice: 820.0,
		subTotalPrice: 820.0,
		baseNetAmount: 820.0,
		netAmount: 820.0,
		baseDiscAmount: 0,
		discountAmount: 0,
		baseTaxAmount: 0,
		taxAmount: 0,
		baseTotalAmount: 820.0,
	},
	{
		poId: 'PO-005',
		number: 'PO-2023-005',
		vendorId: 5,
		vendorName: 'Industrial Supplies Ltd.',
		orderDate: new Date('2023-06-20'),
		DeliveryDate: new Date('2023-07-20'),
		status: PurchaseOrderStatus.Open,
		totalAmount: 2875.0,
		currencyCode: 'USD',
		baseCurrencyCode: 'USD',
		exchangeRate: 1,
		notes: 'Quarterly maintenance supplies',
		createdBy: 105,
		approvedBy: 206,
		approvalDate: new Date('2023-06-21'),
		email: 'sales@industrialsupplies.com',
		buyer: 'Robert Taylor',
		creditTerms: 'Net 90',
		description: 'Industrial cleaning and maintenance supplies',
		remarks: 'Bulk order, please use lift gate truck',
		items: [
			{
				id: 'POI-008',
				name: 'Industrial Cleaner',
				description: '5 gallon bucket',
				convRate: 1,
				orderedQuantity: 20,
				orderUnit: 'buckets',
				baseQuantity: 20,
				baseUnit: 'buckets',
				baseReceivingQty: 0,
				receivedQuantity: 0,
				remainingQuantity: 20,
				unitPrice: 100.0,
				subTotalPrice: 2000.0,
				baseSubTotalPrice: 2000.0,
				status: 'Pending',
				isFOC: false,
				taxIncluded: false,
				taxRate: 0.1,
				taxAmount: 200.0,
				baseTaxAmount: 200.0,
				discountRate: 0.05,
				discountAmount: 100.0,
				baseDiscAmount: 100.0,
				netAmount: 2100.0,
				baseNetAmount: 2100.0,
				totalAmount: 2300.0,
				baseTotalAmount: 2300.0,
				inventoryInfo: {
					onHand: 5,
					onOrdered: 20,
					reorderLevel: 3,
					restockLevel: 15,
					averageMonthlyUsage: 12,
					lastPrice: 95.0,
					lastOrderDate: new Date('2023-03-20'),
					lastVendor: 'Industrial Supplies Ltd.',
				},
			},
			{
				id: 'POI-009',
				name: 'Heavy-Duty Gloves',
				description: 'Box of 100 pairs',
				convRate: 1,
				orderedQuantity: 10,
				orderUnit: 'boxes',
				baseQuantity: 10,
				baseUnit: 'boxes',
				baseReceivingQty: 0,
				receivedQuantity: 0,
				remainingQuantity: 10,
				unitPrice: 50.0,
				subTotalPrice: 500.0,
				baseSubTotalPrice: 500.0,
				status: 'Pending',
				isFOC: false,
				taxIncluded: false,
				taxRate: 0.1,
				taxAmount: 50.0,
				baseTaxAmount: 50.0,
				discountRate: 0.05,
				discountAmount: 25.0,
				baseDiscAmount: 25.0,
				netAmount: 525.0,
				baseNetAmount: 525.0,
				totalAmount: 575.0,
				baseTotalAmount: 575.0,
				inventoryInfo: {
					onHand: 3,
					onOrdered: 10,
					reorderLevel: 2,
					restockLevel: 8,
					averageMonthlyUsage: 6,
					lastPrice: 48.0,
					lastOrderDate: new Date('2023-03-20'),
					lastVendor: 'Industrial Supplies Ltd.',
				},
			},
		],
		baseSubTotalPrice: 2500.0,
		subTotalPrice: 2500.0,
		baseNetAmount: 2625.0,
		netAmount: 2625.0,
		baseDiscAmount: 125.0,
		discountAmount: 125.0,
		baseTaxAmount: 250.0,
		taxAmount: 250.0,
		baseTotalAmount: 2875.0,
	},
	{
		poId: 'PO-006',
		number: 'PO-2023-006',
		vendorId: 6,
		vendorName: 'Global Logistics Co.',
		orderDate: new Date('2023-06-25'),
		DeliveryDate: new Date('2023-07-25'),
		status: PurchaseOrderStatus.Open,
		totalAmount: 22000.0,
		currencyCode: 'USD',
		baseCurrencyCode: 'USD',
		exchangeRate: 1,
		notes: 'Shipping containers for Q3',
		createdBy: 106,
		approvedBy: 207,
		approvalDate: new Date('2023-06-26'),
		email: 'orders@globallogistics.com',
		buyer: 'Jennifer Brown',
		creditTerms: 'Net 60',
		description: 'Shipping containers for international transport',
		remarks: 'Delivery to port required',
		items: [
			{
				id: 'POI-010',
				name: '20ft Shipping Container',
				description: 'Standard dry container',
				convRate: 1,
				orderedQuantity: 5,
				orderUnit: 'units',
				baseQuantity: 5,
				baseUnit: 'units',
				baseReceivingQty: 0,
				receivedQuantity: 0,
				remainingQuantity: 5,
				unitPrice: 4000.0,
				subTotalPrice: 20000.0,
				baseSubTotalPrice: 20000.0,
				status: 'Pending',
				isFOC: false,
				taxIncluded: false,
				taxRate: 0.1,
				taxAmount: 2000.0,
				baseTaxAmount: 2000.0,
				discountRate: 0,
				discountAmount: 0,
				baseDiscAmount: 0,
				netAmount: 22000.0,
				baseNetAmount: 22000.0,
				totalAmount: 22000.0,
				baseTotalAmount: 22000.0,
				inventoryInfo: {
					onHand: 2,
					onOrdered: 5,
					reorderLevel: 2,
					restockLevel: 5,
					averageMonthlyUsage: 3,
					lastPrice: 3800.0,
					lastOrderDate: new Date('2023-03-15'),
					lastVendor: 'Global Logistics Co.',
				},
			},
		],
		baseSubTotalPrice: 20000.0,
		subTotalPrice: 20000.0,
		baseNetAmount: 22000.0,
		netAmount: 22000.0,
		baseDiscAmount: 0,
		discountAmount: 0,
		baseTaxAmount: 2000.0,
		taxAmount: 2000.0,
		baseTotalAmount: 22000.0,
	},
	{
		poId: 'PO-007',
		number: 'PO-2023-007',
		vendorId: 7,
		vendorName: 'Green Energy Solutions',
		orderDate: new Date('2023-06-30'),
		DeliveryDate: new Date('2023-08-15'),
		status: PurchaseOrderStatus.Open,
		totalAmount: 57500.0,
		currencyCode: 'USD',
		baseCurrencyCode: 'USD',
		exchangeRate: 1,
		notes: 'Solar panel installation project',
		createdBy: 107,
		approvedBy: 208,
		approvalDate: new Date('2023-07-01'),
		email: 'orders@greenenergy.com',
		buyer: 'David Lee',
		creditTerms: 'Net 90',
		description: 'Solar panels and inverters',
		remarks: 'Installation date to be confirmed',
		items: [
			{
				id: 'POI-011',
				name: 'Solar Panel',
				description: '400W Monocrystalline',
				convRate: 1,
				orderedQuantity: 100,
				orderUnit: 'pieces',
				baseQuantity: 100,
				baseUnit: 'pieces',
				baseReceivingQty: 0,
				receivedQuantity: 0,
				remainingQuantity: 100,
				unitPrice: 400.0,
				subTotalPrice: 40000.0,
				baseSubTotalPrice: 40000.0,
				status: 'Pending',
				isFOC: false,
				taxIncluded: false,
				taxRate: 0.1,
				taxAmount: 4000.0,
				baseTaxAmount: 4000.0,
				discountRate: 0.05,
				discountAmount: 2000.0,
				baseDiscAmount: 2000.0,
				netAmount: 42000.0,
				baseNetAmount: 42000.0,
				totalAmount: 46000.0,
				baseTotalAmount: 46000.0,
				inventoryInfo: {
					onHand: 20,
					onOrdered: 100,
					reorderLevel: 15,
					restockLevel: 50,
					averageMonthlyUsage: 40,
					lastPrice: 380.0,
					lastOrderDate: new Date('2023-05-01'),
					lastVendor: 'Green Energy Solutions',
				},
			},
			{
				id: 'POI-012',
				name: 'Inverter',
				description: '5kW Grid-Tie Inverter',
				convRate: 1,
				orderedQuantity: 10,
				orderUnit: 'pieces',
				baseQuantity: 10,
				baseUnit: 'pieces',
				baseReceivingQty: 0,
				receivedQuantity: 0,
				remainingQuantity: 10,
				unitPrice: 1000.0,
				subTotalPrice: 10000.0,
				baseSubTotalPrice: 10000.0,
				status: 'Pending',
				isFOC: false,
				taxIncluded: false,
				taxRate: 0.1,
				taxAmount: 1000.0,
				baseTaxAmount: 1000.0,
				discountRate: 0.05,
				discountAmount: 500.0,
				baseDiscAmount: 500.0,
				netAmount: 10500.0,
				baseNetAmount: 10500.0,
				totalAmount: 11500.0,
				baseTotalAmount: 11500.0,
				inventoryInfo: {
					onHand: 5,
					onOrdered: 10,
					reorderLevel: 3,
					restockLevel: 8,
					averageMonthlyUsage: 6,
					lastPrice: 950.0,
					lastOrderDate: new Date('2023-05-01'),
					lastVendor: 'Green Energy Solutions',
				},
			},
		],
		baseSubTotalPrice: 50000.0,
		subTotalPrice: 50000.0,
		baseNetAmount: 52500.0,
		netAmount: 52500.0,
		baseDiscAmount: 2500.0,
		discountAmount: 2500.0,
		baseTaxAmount: 5000.0,
		taxAmount: 5000.0,
		baseTotalAmount: 57500.0,
	},
];

export interface PurchaseRequest {
	id: string;
	refNumber: string;
	date: Date;
	type: string;
	description: string;
	requestorId: string;
	requestor: {
		name: string;
		id: string;
		department: string;
	};
	status: DocumentStatus | string;
	workflowStatus: WorkflowStatus | string;
	currentWorkflowStage: WorkflowStage | string;
	location: string;
	department: string;
	jobCode: string;
	estimatedTotal: number;
	vendor: string;
	vendorId: number;
	deliveryDate: Date;
	currency: string;
	baseCurrencyCode: string;
	baseSubTotalPrice: number;
	subTotalPrice: number;
	baseNetAmount: number;
	netAmount: number;
	baseDiscAmount: number;
	discountAmount: number;
	baseTaxAmount: number;
	taxAmount: number;
	baseTotalAmount: number;
	totalAmount: number;
}

export const purchaseRequests: PurchaseRequest[] = [
	{
		id: 'PR-001',
		refNumber: 'PR-2023-001',
		date: new Date('2023-06-15'),
		type: 'General Purchase',
		description: 'Office Supplies',
		requestorId: 'user-001',
		requestor: {
			name: 'John Doe',
			id: 'user-001',
			department: 'Administration',
		},
		status: 'Submitted',
		workflowStatus: 'pending',
		currentWorkflowStage: 'Initial Review',
		location: 'Head Office',
		department: 'Administration',
		jobCode: 'JOB-001',
		estimatedTotal: 500,
		vendor: 'Office Supplies Co.',
		vendorId: 1,
		deliveryDate: new Date('2023-07-01'),
		currency: 'USD',
		baseCurrencyCode: 'USD',
		baseSubTotalPrice: 450,
		subTotalPrice: 450,
		baseNetAmount: 450,
		netAmount: 450,
		baseDiscAmount: 0,
		discountAmount: 0,
		baseTaxAmount: 50,
		taxAmount: 50,
		baseTotalAmount: 500,
		totalAmount: 500,
	},
	{
		id: 'PR-002',
		refNumber: 'PR-2023-002',
		date: new Date('2023-06-14'),
		type: 'Market List',
		description: 'Weekly Groceries',
		requestorId: 'user-002',
		requestor: {
			name: 'Jane Smith',
			id: 'user-002',
			department: 'Catering',
		},
		status: 'Approved',
		workflowStatus: 'approved',
		currentWorkflowStage: 'Procurement',
		location: 'Kitchen',
		department: 'Catering',
		jobCode: 'JOB-002',
		estimatedTotal: 750,
		vendor: 'Fresh Foods Inc.',
		vendorId: 2,
		deliveryDate: new Date('2023-06-20'),
		currency: 'USD',
		baseCurrencyCode: 'USD',
		baseSubTotalPrice: 680,
		subTotalPrice: 680,
		baseNetAmount: 680,
		netAmount: 680,
		baseDiscAmount: 0,
		discountAmount: 0,
		baseTaxAmount: 70,
		taxAmount: 70,
		baseTotalAmount: 750,
		totalAmount: 750,
	},
	{
		id: 'PR-003',
		refNumber: 'PR-2023-003',
		date: new Date('2023-06-13'),
		type: 'Asset Purchase',
		description: 'Laptop Computers',
		requestorId: 'user-003',
		requestor: {
			name: 'Mike Johnson',
			id: 'user-003',
			department: 'IT',
		},
		status: 'Rejected',
		workflowStatus: 'rejected',
		currentWorkflowStage: 'Final Review',
		location: 'IT Department',
		department: 'IT',
		jobCode: 'JOB-003',
		estimatedTotal: 3000,
		vendor: 'Tech Solutions Ltd.',
		vendorId: 3,
		deliveryDate: new Date('2023-07-15'),
		currency: 'USD',
		baseCurrencyCode: 'USD',
		baseSubTotalPrice: 2700,
		subTotalPrice: 2700,
		baseNetAmount: 2700,
		netAmount: 2700,
		baseDiscAmount: 0,
		discountAmount: 0,
		baseTaxAmount: 300,
		taxAmount: 300,
		baseTotalAmount: 3000,
		totalAmount: 3000,
	},
	{
		id: 'PR-004',
		refNumber: 'PR-2023-004',
		date: new Date('2023-06-12'),
		type: 'General Purchase',
		description: 'Office Furniture',
		requestorId: 'user-004',
		requestor: {
			name: 'Emily Brown',
			id: 'user-004',
			department: 'HR',
		},
		status: 'Draft',
		workflowStatus: 'draft',
		currentWorkflowStage: 'Draft',
		location: 'HR Department',
		department: 'HR',
		jobCode: 'JOB-004',
		estimatedTotal: 1200,
		vendor: 'Office Furniture Co.',
		vendorId: 4,
		deliveryDate: new Date('2023-07-10'),
		currency: 'USD',
		baseCurrencyCode: 'USD',
		baseSubTotalPrice: 1090,
		subTotalPrice: 1090,
		baseNetAmount: 1090,
		netAmount: 1090,
		baseDiscAmount: 0,
		discountAmount: 0,
		baseTaxAmount: 110,
		taxAmount: 110,
		baseTotalAmount: 1200,
		totalAmount: 1200,
	},
	{
		id: 'PR-005',
		refNumber: 'PR-2023-005',
		date: new Date('2023-06-11'),
		type: 'Market List',
		description: 'Monthly Supplies',
		requestorId: 'user-005',
		requestor: {
			name: 'David Lee',
			id: 'user-005',
			department: 'Facilities',
		},
		status: 'Submitted',
		workflowStatus: 'pending',
		currentWorkflowStage: 'Department Approval',
		location: 'Facilities Department',
		department: 'Facilities',
		jobCode: 'JOB-005',
		estimatedTotal: 900,
		vendor: 'Supply Depot',
		vendorId: 5,
		deliveryDate: new Date('2023-06-25'),
		currency: 'USD',
		baseCurrencyCode: 'USD',
		baseSubTotalPrice: 820,
		subTotalPrice: 820,
		baseNetAmount: 820,
		netAmount: 820,
		baseDiscAmount: 0,
		discountAmount: 0,
		baseTaxAmount: 80,
		taxAmount: 80,
		baseTotalAmount: 900,
		totalAmount: 900,
	},
	{
		id: 'PR-006',
		refNumber: 'PR-2023-006',
		date: new Date('2023-06-10'),
		type: 'Asset Purchase',
		description: 'Server Equipment',
		requestorId: 'user-006',
		requestor: {
			name: 'Sarah Connor',
			id: 'user-006',
			department: 'IT',
		},
		status: 'Approved',
		workflowStatus: 'approved',
		currentWorkflowStage: 'Procurement',
		location: 'Server Room',
		department: 'IT',
		jobCode: 'JOB-006',
		estimatedTotal: 5000,
		vendor: 'Server Solutions Inc.',
		vendorId: 6,
		deliveryDate: new Date('2023-07-20'),
		currency: 'USD',
		baseCurrencyCode: 'USD',
		baseSubTotalPrice: 4550,
		subTotalPrice: 4550,
		baseNetAmount: 4550,
		netAmount: 4550,
		baseDiscAmount: 0,
		discountAmount: 0,
		baseTaxAmount: 450,
		taxAmount: 450,
		baseTotalAmount: 5000,
		totalAmount: 5000,
	},
	{
		id: 'PR-007',
		refNumber: 'PR-2023-007',
		date: new Date('2023-06-09'),
		type: 'General Purchase',
		description: 'Marketing Materials',
		requestorId: 'user-007',
		requestor: {
			name: 'Tom Wilson',
			id: 'user-007',
			department: 'Marketing',
		},
		status: 'Submitted',
		workflowStatus: 'pending',
		currentWorkflowStage: 'Financial Review',
		location: 'Marketing Department',
		department: 'Marketing',
		jobCode: 'JOB-007',
		estimatedTotal: 800,
		vendor: 'Print Masters',
		vendorId: 7,
		deliveryDate: new Date('2023-06-30'),
		currency: 'USD',
		baseCurrencyCode: 'USD',
		baseSubTotalPrice: 730,
		subTotalPrice: 730,
		baseNetAmount: 730,
		netAmount: 730,
		baseDiscAmount: 0,
		discountAmount: 0,
		baseTaxAmount: 70,
		taxAmount: 70,
		baseTotalAmount: 800,
		totalAmount: 800,
	},
	{
		id: 'PR-008',
		refNumber: 'PR-2023-008',
		date: new Date('2023-06-08'),
		type: 'Market List',
		description: 'Event Catering',
		requestorId: 'user-008',
		requestor: {
			name: 'Alice Johnson',
			id: 'user-008',
			department: 'Events',
		},
		status: 'Approved',
		workflowStatus: 'approved',
		currentWorkflowStage: 'Procurement',
		location: 'Event Hall',
		department: 'Events',
		jobCode: 'JOB-008',
		estimatedTotal: 1500,
		vendor: 'Catering Experts',
		vendorId: 8,
		deliveryDate: new Date('2023-06-15'),
		currency: 'USD',
		baseCurrencyCode: 'USD',
		baseSubTotalPrice: 1360,
		subTotalPrice: 1360,
		baseNetAmount: 1360,
		netAmount: 1360,
		baseDiscAmount: 0,
		discountAmount: 0,
		baseTaxAmount: 140,
		taxAmount: 140,
		baseTotalAmount: 1500,
		totalAmount: 1500,
	},
	{
		id: 'PR-009',
		refNumber: 'PR-2023-009',
		date: new Date('2023-06-07'),
		type: 'Asset Purchase',
		description: 'Company Vehicles',
		requestorId: 'user-009',
		requestor: {
			name: 'Robert Davis',
			id: 'user-009',
			department: 'Operations',
		},
		status: 'Rejected',
		workflowStatus: 'rejected',
		currentWorkflowStage: 'Final Review',
		location: 'Operations Department',
		department: 'Operations',
		jobCode: 'JOB-009',
		estimatedTotal: 50000,
		vendor: 'Auto Dealership',
		vendorId: 9,
		deliveryDate: new Date('2023-08-01'),
		currency: 'USD',
		baseCurrencyCode: 'USD',
		baseSubTotalPrice: 45500,
		subTotalPrice: 45500,
		baseNetAmount: 45500,
		netAmount: 45500,
		baseDiscAmount: 0,
		discountAmount: 0,
		baseTaxAmount: 4500,
		taxAmount: 4500,
		baseTotalAmount: 50000,
		totalAmount: 50000,
	},
	{
		id: 'PR-010',
		refNumber: 'PR-2023-010',
		date: new Date('2023-06-06'),
		type: 'General Purchase',
		description: 'Training Materials',
		requestorId: 'user-010',
		requestor: {
			name: 'Emma White',
			id: 'user-010',
			department: 'HR',
		},
		status: 'Draft',
		workflowStatus: 'draft',
		currentWorkflowStage: 'Draft',
		location: 'Training Room',
		department: 'HR',
		jobCode: 'JOB-010',
		estimatedTotal: 300,
		vendor: 'Training Supplies Inc.',
		vendorId: 10,
		deliveryDate: new Date('2023-06-20'),
		currency: 'USD',
		baseCurrencyCode: 'USD',
		baseSubTotalPrice: 270,
		subTotalPrice: 270,
		baseNetAmount: 270,
		netAmount: 270,
		baseDiscAmount: 0,
		discountAmount: 0,
		baseTaxAmount: 30,
		taxAmount: 30,
		baseTotalAmount: 300,
		totalAmount: 300,
	},
];