// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Project Carmen_Inventory {
  database_type: 'PostgreSQL'
  Note: 'Carmen Inventory Project 2024'
}

TABLE CARMEN_SYSTEM.user_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  username varchar(30) [unique, not null]
  email varchar(255) [not null]

  is_active bool [default: false]
  is_consent bool [default: false]
  consent timestamp [null]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  indexes {
    username [name: "user_username_idx"]
    email [name: "user_email_idx"]
  }
}

TABLE CARMEN_SYSTEM.password_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  user_id uuid [not null, ref: > CARMEN_SYSTEM.user_table.id]
  hash text [not null]
  is_active bool [default: false]
  expiredOn date [not null, default: `now() + '90 day'::interval`]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  indexes {
    user_id [name: 'password_user_id_idx']
  }
}

TABLE CARMEN_SYSTEM.user_profile_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  user_id uuid [ref: - CARMEN_SYSTEM.user_table.id]

  firstname varchar(100) [not null, default: '']
  middlename varchar(100) [default: '']
  lastname varchar(100) [default: '']

  bio json [null, default: '{}']

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  indexes {
    user_id [name: "userprofile_user_id_idx"]
   (firstname, lastname) [name: "userprofile_firstname_lastname_idx"]
  }
}

TABLE CARMEN_SYSTEM.module_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  name        varchar   [not null, unique]
  description text

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  indexes {
    name [name: "module_name_id_u"]
  }
}

TABLE CARMEN_SYSTEM.business_unit_module_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  business_unit_id uuid [not null, ref: > CARMEN_SYSTEM.business_unit_table.id]
  module_id uuid [not null, ref: > CARMEN_SYSTEM.module_table.id]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  indexes {
    (business_unit_id, module_id) [name: "businessunitmodule_business_unit_id_module_id_u"]
  }
}

Enum CARMEN_SYSTEM.enum_subscription_status {
  active
  inactive
  expired
}

TABLE CARMEN_SYSTEM.subscription_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  cluster_id uuid [not null, ref: > CARMEN_SYSTEM.cluster_table.id]

  subscription_number varchar [not null]
  start_date date [not null]
  end_date date [not null]

  status CARMEN_SYSTEM.enum_subscription_status [not null]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  indexes {
    (cluster_id, subscription_number) [unique, name: "subscription_cluster_id_subscription_number_u"]
  }
}

TABLE CARMEN_SYSTEM.subscription_detail_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]

  subscription_id uuid [not null, ref: > CARMEN_SYSTEM.subscription_table.id]
  business_unit_id uuid [not null, ref: > CARMEN_SYSTEM.business_unit_table.id]
  module_id uuid [not null, ref: > CARMEN_SYSTEM.module_table.id]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  indexes {
    (subscription_id, business_unit_id, module_id) [unique, name: "subscriptiondetail_subscription_id_business_unit_id_module_id_u"]
  }
}

TABLE CARMEN_SYSTEM.cluster_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  code varchar(30) [not null, unique]
  name text [not null, unique]
  is_active bool [default: true]

  info json [null]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  indexes {
    code [unique, name: "cluster_code_u"]
    name [unique, name: "cluster_name_u"]
  }
}

TABLE CARMEN_SYSTEM.business_unit_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  cluster_id uuid [not null, ref: > CARMEN_SYSTEM.cluster_table.id]

  code varchar(30) [not null]
  name text [not null]
  description text

  is_hq bool [default: true]
  is_active bool [default: true]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  indexes {
    cluster_id [name: "tenant_clusertid_idx"]
    code [name: "businessunit_code_idx"]
    (cluster_id, code) [unique, name: "businessunit_clusertid_code_u"]
  }
}

TABLE CARMEN_SYSTEM.user_business_unit_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  user_id uuid [ref: > CARMEN_SYSTEM.user_table.id]
  business_unit_id uuid [ref: > CARMEN_SYSTEM.business_unit_table.id]

  is_active bool [default: true]
  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  indexes {
    (user_id, business_unit_id) [unique, name: "usertenant_user_id_business_unit_id_u"]
  }
}

TABLE CARMEN_SYSTEM.notification_preference_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  user_id uuid [not null, unique, ref: > CARMEN_SYSTEM.user_table.id]

  is_email bool [not null, default: false]
  is_sms bool [default: false]
  is_in_app bool [default: true]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  indexes {
    user_id [name: "notificationpreference_user_id_u"]
  }
}

TABLE CARMEN_SYSTEM.notification_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  user_id uuid [not null, ref: > CARMEN_SYSTEM.user_table.id]
  message text
  is_read bool [default: false]
  is_sent bool [default: false]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  indexes {
  }
}

TABLE CARMEN_SYSTEM.application_role_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  business_unit_id uuid [not null, ref: > CARMEN_SYSTEM.business_unit_table.id]
  name        varchar   [not null, unique]
  description text

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  indexes {
    name [name: "application_role_name_idx"]
    (business_unit_id, name) [unique, name: "application_role_business_unit_id_name_u"]
  }
}

ENUM CARMEN_SYSTEM.enum_permission_action{
  view
  view_all
  create
  update
  delete
  own_delete
  print
  export
}

TABLE CARMEN_SYSTEM.permission_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  group varchar [not null]
  name varchar   [ not null]
  action CARMEN_SYSTEM.enum_permission_action [not null]
  description text

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  indexes {
    (group,name,action) [unique, name: "permission_group_name_action_u"]
  }
}

TABLE CARMEN_SYSTEM.user_application_role_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  user_id   uuid [not null, ref: > CARMEN_SYSTEM.user_table.id]
  application_role_id   uuid [not null, ref: > CARMEN_SYSTEM.application_role_table.id]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  Indexes {
    (user_id, application_role_id) [unique, name: "userapplicationrole_user_id_application_role_id_u"]
  }
}

TABLE CARMEN_SYSTEM.application_role_permission_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  application_role_id       uuid [not null, ref: > CARMEN_SYSTEM.application_role_table.id]
  permission_id uuid [not null, ref: > CARMEN_SYSTEM.permission_table.id]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid [ref: > CARMEN_SYSTEM.user_table.id]

  Indexes {
    (application_role_id, permission_id) [unique, name: "applicationrolepermission_application_role_id_permission_id_u"]
  }
}

enum TENANT_DUMMY.enum_activity_action {
  read
  create
  update
  delete
  login
  other
}

enum TENANT_DUMMY.enum_activity_entity_type {
  user
  business_unit
  product
  location
  department
  unit
  currency
  exchange_rate
  menu
  delivery_point
  purchase_request
  purchase_request_item
  purchase_order
  purchase_order_item
  inventory_transaction
  inventory_adjustment
  store_requisition
  store_requisition_item
  stock_in
  stock_out
  stock_adjustment
  stock_transfer
  stock_count
  stock_take
  stock_take_item
  other
}

TABLE TENANT_DUMMY.global_activity_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  action TENANT_DUMMY.enum_activity_action
  entity_type TENANT_DUMMY.enum_activity_entity_type
  entity_id uuid
  actor_id uuid
  meta_data json [null]
  old_data json [null]
  new_data json [null]
  ip_address text [null]
  user_agent text [null]
  description text

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid

  indexes {
    (entity_type, entity_id) [name: 'global_activity_entitytype_entityid_idx']
  }

}

TABLE TENANT_DUMMY.menu_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  name varchar(5) [unique, not null]
  description text

  is_active bool [default: true]
  is_visible bool [default: true]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    name [name: "menu_name_u"]
  }
}

TABLE TENANT_DUMMY.currency_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  code varchar(3) [unique, not null]
  name varchar(100) [not null]
  symbol varchar(5)
  description text [default: ""]

  is_active bool [default: true]
  rate float [default: 1]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    code [name: "currency_code_u"]
  }
}

TABLE TENANT_DUMMY.exchange_rate_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]

  at_date timestamp [default: `now()`]
  currency_id uuid [ref: > TENANT_DUMMY.currency_table.id]
  rate float [default: 1]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    (at_date, currency_id) [unique, name: "exchangerate_at_date_currency_id_u"]
  }
}

enum TENANT_DUMMY.enum_location_type {
  inventory
  direct
  consignment
}

TABLE TENANT_DUMMY.location_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  name varchar [unique, not null]

  location_type TENANT_DUMMY.enum_location_type [not null]

  description text
  is_active bool [default: true]

  delivery_point_id uuid [ref: > TENANT_DUMMY.delivery_point_table.id]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    name [name: "location_name_u"]
  }
}

TABLE TENANT_DUMMY.delivery_point_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  name varchar [unique, not null]
  is_active bool [default: true]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    name [name: "deliverypoint_name_u"]
  }
}

TABLE TENANT_DUMMY.unit_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  name varchar [unique, not null]
  description text
  is_active bool [default: true]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    name [name: "unit_name_u"]
  }
}

Enum TENANT_DUMMY.enum_unit_type {
  order_unit
  inventory_unit
  recipe_unit
}

TABLE TENANT_DUMMY.unit_conversion_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  product_id uuid [ref: > TENANT_DUMMY.product_table.id]
  unit_type TENANT_DUMMY.enum_unit_type [not null]
  from_unit_id uuid [ref: > TENANT_DUMMY.unit_table.id]
  from_unit_qty float [default: 1]
  to_unit_id uuid [ref: > TENANT_DUMMY.unit_table.id]
  to_unit_qty float [default: 1]
  description text

  is_active bool [default: true]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    (product_id, unit_type, from_unit_id, to_unit_id) [name: "unitconversion_product_id_unit_type_from_unit_id_to_unit_id_u"]
  }
}

TABLE TENANT_DUMMY.department_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  name varchar [unique, not null]
  description text
  is_active bool [default: true]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    name [name: "department_name_u"]
  }
}

TABLE TENANT_DUMMY.product_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  code varchar [unique, not null]
  name varchar [unique, not null]
  description text

  primary_unit uuid [not null, ref: > TENANT_DUMMY.unit_table.id]

  is_active bool [default: true]
  
  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    code [name: "product_code_u"]
    name [name: "product_name_u"]

  }
}

TABLE TENANT_DUMMY.product_info_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  product_id uuid [unique, not null, ref: - TENANT_DUMMY.product_table.id]
  price Float

  info json [null]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    product_id [name: "productinfo_product_id_u"]
  }
}

TABLE TENANT_DUMMY.product_category_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  code varchar [unique, not null]
  name varchar [unique, not null]
  description text
  is_active bool [default: true]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    code [name: "productcategory_code_u"]
    name [name: "productcategory_name_u"]
  }
}

TABLE TENANT_DUMMY.product_sub_category_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  code varchar [unique, not null]
  name varchar [unique, not null]
  description text
  is_active bool [default: true]
  product_category_id uuid [ref: > TENANT_DUMMY.product_category_table.id]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    code [name: "productsubcategory_code_u"]
    name [name: "productsubcategory_name_u"]
  }
}

TABLE TENANT_DUMMY.product_item_group_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  code varchar [unique, not null]
  name varchar [unique, not null]
  description text
  is_active bool [default: true]
  product_subcategory_id uuid [ref: > TENANT_DUMMY.product_sub_category_table.id]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    code [name: "productitemgroup_code_u"]
    name [name: "productitemgroup_name_u"]
  }
}

TABLE TENANT_DUMMY.purchase_request_type_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  code varchar [unique, not null]
  name varchar [unique, not null]
  description text
  is_active bool [default: true]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    code [name: "PRtype_code_u"]
    name [name: "PRtype_name_u"]
  }
}

enum TENANT_DUMMY.enum_purchase_request_doc_status {
  draft
  work_in_process
  complete
}

TABLE TENANT_DUMMY.purchase_request_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  reference_name varchar [unique, not null]


  purchase_request_date date
  purchase_request_type_id uuid [ref: > TENANT_DUMMY.purchase_request_type_table.id]

  purchase_request_status TENANT_DUMMY.enum_purchase_request_doc_status [default: 'draft']

  requestor_id uuid
  department_id uuid

  is_active bool [default: true]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    reference_name [name: "PR0_reference_name_u"]
  }
}

TABLE TENANT_DUMMY.purchase_request_detail_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  purchase_request_id uuid [ref: > TENANT_DUMMY.purchase_request_table.id]

  location_id uuid
  product_id uuid
  unit_id uuid

  description text

  requested_qty float
  approved_qty float

  currency_id uuid
  currency_rate float

  price numeric(15,5)
  total_price numeric(15,5)

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

   indexes {
  }
}

enum TENANT_DUMMY.enum_purchase_request_workflow_status {
  draft
  pending
  review
  accept
}

TABLE TENANT_DUMMY.purchase_request_detail_workflow_table {

   id uuid [not null, pk, default: `gen_random_uuid()`]
  purchase_request_detail_id uuid [ref: > TENANT_DUMMY.purchase_request_detail_table.id]

  purchase_request_workflow_status TENANT_DUMMY.enum_purchase_request_workflow_status [default: 'draft']

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 
  
}


enum TENANT_DUMMY.enum_purchase_order_doc_status {
  open 
  voided 
  closed 
  draft 
  sent
  partial
  fully_received 
  cancelled 
  deleted 
}

TABLE TENANT_DUMMY.purchase_order_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  name varchar [unique, not null]
  purchase_order_status TENANT_DUMMY.enum_purchase_order_doc_status [default: 'open']

  description text

  order_date date

  is_active bool [default: true]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid
  
  indexes {
    name [name: "PO_name_u"]
  }
}

TABLE TENANT_DUMMY.purchase_order_detail_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]

  name varchar [unique]
  description text
  is_active bool [default: true]

  purchase_order_id uuid [ref: > TENANT_DUMMY.purchase_order_table.id]

  purchase_request_detail_id uuid [ref: > TENANT_DUMMY.purchase_request_detail_table.id]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    name [name: "PO1_name_u"]
  }
}


TABLE TENANT_DUMMY.vendor_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  name varchar [unique, not null]
  description text
  is_active bool [default: true]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    name [name: "vendor_name_u"]
  }
}


TABLE TENANT_DUMMY.contact_type_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  name uuid [unique, not null]
  description text
  is_active bool [default: true]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    name [name: "contacttype_name_u"]
  }

  note:'''
  contact_type_id is not unique because a vendor can have multiple contacts of the same type
  sample:
  vendor can have multiple phone numbers, email addresses, etc.
  '''
}

TABLE TENANT_DUMMY.vendor_contact_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  vendor_id uuid [ref: > TENANT_DUMMY.vendor_table.id]
  contact_type_id uuid [not null, ref: > TENANT_DUMMY.contact_type_table.id]
  description text
  is_active bool [default: true]

  info json [null]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    (vendor_id, contact_type_id) [unique, name: "vendorcontact_vendor_id_contact_type_id_u"]
  }
}


TABLE TENANT_DUMMY.address_type_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  name uuid [unique, not null]
  description text
  is_active bool [default: true]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    name [name: "addresstype_name_u"]
  }

  note:'''
  address_type_id is not unique because a vendor can have multiple addresses of the same type
  sample:
  vendor can have multiple physical addresses, mailing addresses, etc.
  '''
}

TABLE TENANT_DUMMY.vendor_address_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  vendor_id uuid [ref: > TENANT_DUMMY.vendor_table.id]
  address_type_id uuid [not null, ref: > TENANT_DUMMY.address_type_table.id]

  address json [null]
  is_active bool [default: true]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    (vendor_id, address_type_id) [unique, name: "vendorcontact_vendor_id_address_type_id_u"]
  }
}

TABLE TENANT_DUMMY.product_vendor_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]

  product_id uuid [ref: > TENANT_DUMMY.product_table.id]
  vendor_id uuid [ref: > TENANT_DUMMY.vendor_table.id]

  description text
  is_active bool [default: true]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    (vendor_id, product_id) [unique, name: "productvendor_vendor_id_product_id_u"]
  }
}

enum TENANT_DUMMY.enum_inventory_doc_type {
  good_receive_note
  credit_note
  store_requisition
  issue
  adjust
  stock_in
  stock_out
}

TABLE TENANT_DUMMY.inventory_transaction_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  name varchar [unique, not null]
  inventory_doc_type TENANT_DUMMY.enum_inventory_doc_type [not null]

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

}

TABLE TENANT_DUMMY.inventory_transaction_detail_table {

  id uuid [not null, pk, default: `gen_random_uuid()`]
  inventory_transaction_id uuid [not null, ref: > TENANT_DUMMY.inventory_transaction_table.id]

  from_lot_name uuid
  current_lot_name varchar

  qty decimal
  cost numeric(15,5)

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

}

TABLE TENANT_DUMMY.inventory_transaction_cf_table {

  id uuid [not null, pk, default: `gen_random_uuid()`]
  inventory_transaction_detail_id uuid [ not null, ref: - TENANT_DUMMY.inventory_transaction_detail_table.id]
  
  lot_name varchar
  lot_index integer [not null, default: 1]

  qty decimal
  cost numeric(15,5)

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    (lot_name, lot_index) [unique, name: "inv2_lotname_lot_index_u"]
  }
}

TABLE TENANT_DUMMY.good_receive_note_table {

  id uuid [not null, pk, default: `gen_random_uuid()`]
  inventory_transaction_id uuid [not null, ref: - TENANT_DUMMY.inventory_transaction_table.id]

  name varchar

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

}

TABLE TENANT_DUMMY.good_receive_note_detail_table {

  id uuid [not null, pk, default: `gen_random_uuid()`]
  good_receive_note_id uuid [not null, ref: > TENANT_DUMMY.good_receive_note_table.id]
  
  name varchar

  qty decimal

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

}

TABLE TENANT_DUMMY.store_requisition_table {

  id uuid [not null, pk, default: `gen_random_uuid()`]
  inventory_transaction_id uuid [not null, ref: - TENANT_DUMMY.inventory_transaction_table.id]
  
  name varchar

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

}

TABLE TENANT_DUMMY.store_requisition_detail_table {

  id uuid [not null, pk, default: `gen_random_uuid()`]
  store_requisition_id uuid [not null, ref: > TENANT_DUMMY.store_requisition_table.id]
  
  name varchar

  qty decimal

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

}


TABLE TENANT_DUMMY.stock_in_table {

  id uuid [not null, pk, default: `gen_random_uuid()`]
  inventory_transaction_id uuid [not null, ref: - TENANT_DUMMY.inventory_transaction_table.id]
  
  name varchar

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

}

TABLE TENANT_DUMMY.stock_in_detail_table {

  id uuid [not null, pk, default: `gen_random_uuid()`]
  stock_in_id uuid [not null, ref: > TENANT_DUMMY.stock_in_table.id]
  
  name varchar

  qty decimal

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

}


TABLE TENANT_DUMMY.stock_out_table {

  id uuid [not null, pk, default: `gen_random_uuid()`]
  inventory_transaction_id uuid [not null, ref: - TENANT_DUMMY.inventory_transaction_table.id]
  
  name varchar

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

}

TABLE TENANT_DUMMY.stock_out_detail_table {

  id uuid [not null, pk, default: `gen_random_uuid()`]
  stock_in_id uuid [not null, ref: > TENANT_DUMMY.stock_out_table.id]
  
  name varchar

  qty decimal

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid 

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

}

TABLE TENANT_DUMMY.inventory_adjustment_table {

  id uuid [not null, pk, default: `gen_random_uuid()`]
  inventory_transaction_id uuid [not null, ref: - TENANT_DUMMY.inventory_transaction_table.id]

  name varchar

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    name [name: "inventoryadjustment_name_u"]
  }
}

TABLE TENANT_DUMMY.inventory_adjustment_detail_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  inventory_adjustment_id uuid [not null, ref: > TENANT_DUMMY.inventory_adjustment_table.id]

  name varchar

  qty decimal

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    (inventory_adjustment_id, name) [unique, name: "inventoryadjustmentdetail_inventory_adjustment_id_name_u"]
  }
}

TABLE TENANT_DUMMY.credit_note_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  inventory_transaction_id uuid [not null, ref: - TENANT_DUMMY.inventory_transaction_table.id]

  name varchar

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    name [name: "creditnote_name_u"]
  }
}

TABLE TENANT_DUMMY.credit_note_detail_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]  
  credit_note_id uuid [not null, ref: > TENANT_DUMMY.credit_note_table.id]

  name varchar

  qty decimal
  amount numeric(15,5)

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid

  indexes {
    (credit_note_id, name) [unique, name: "creditnotedetail_credit_note_id_name_u"]
  }
}

TABLE TENANT_DUMMY.stock_take_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  inventory_transaction_id uuid [not null, ref: - TENANT_DUMMY.inventory_transaction_table.id]

  name varchar

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid
}

TABLE TENANT_DUMMY.stock_take_detail_table {
  id uuid [not null, pk, default: `gen_random_uuid()`]
  stock_take_id uuid [not null, ref: > TENANT_DUMMY.stock_take_table.id]

  name varchar
  
  qty decimal

  created_at timestamp [default: `CURRENT_TIMESTAMP` ]
  created_by_id uuid

  updated_at timestamp [null, default: `CURRENT_TIMESTAMP`]
  updated_by_id uuid
}
