-- Insert Currency ISO-4217 Codes
INSERT INTO "CARMEN_SYSTEM"."tb_currency_iso" (id, iso_code, symbol, name) VALUES
(gen_random_uuid(), 'AED', 'د.إ', 'United Arab Emirates dirham'),
(gen_random_uuid(), 'AFN', '؋', 'Afghan afghani'),
(gen_random_uuid(), 'ALL', 'L', 'Albanian lek'),
(gen_random_uuid(), 'AMD', '֏', 'Armenian dram'),
(gen_random_uuid(), 'ANG', 'ƒ', 'Netherlands Antillean guilder'),
(gen_random_uuid(), 'AOA', 'Kz', 'Angolan kwanza'),
(gen_random_uuid(), 'ARS', '$', 'Argentine peso'),
(gen_random_uuid(), 'AUD', '$', 'Australian dollar'),
(gen_random_uuid(), 'AWG', 'ƒ', 'Aruban florin'),
(gen_random_uuid(), 'AZN', '₼', 'Azerbaijani manat'),
(gen_random_uuid(), 'BAM', 'KM', 'Bosnia and Herzegovina convertible mark'),
(gen_random_uuid(), 'BBD', '$', 'Barbados dollar'),
(gen_random_uuid(), 'BDT', '৳', 'Bangladeshi taka'),
(gen_random_uuid(), 'BGN', 'лв', 'Bulgarian lev'),
(gen_random_uuid(), 'BHD', '.د.ب', 'Bahraini dinar'),
(gen_random_uuid(), 'BIF', 'FBu', 'Burundian franc'),
(gen_random_uuid(), 'BMD', '$', 'Bermudian dollar'),
(gen_random_uuid(), 'BND', '$', 'Brunei dollar'),
(gen_random_uuid(), 'BOB', 'Bs.', 'Boliviano'),
(gen_random_uuid(), 'BRL', 'R$', 'Brazilian real'),
(gen_random_uuid(), 'BSD', '$', 'Bahamian dollar'),
(gen_random_uuid(), 'BTN', 'Nu.', 'Bhutanese ngultrum'),
(gen_random_uuid(), 'BWP', 'P', 'Botswana pula'),
(gen_random_uuid(), 'BYN', 'Br', 'Belarusian ruble'),
(gen_random_uuid(), 'BZD', 'BZ$', 'Belize dollar'),
(gen_random_uuid(), 'CAD', '$', 'Canadian dollar'),
(gen_random_uuid(), 'CDF', 'FC', 'Congolese franc'),
(gen_random_uuid(), 'CHF', 'Fr.', 'Swiss franc'),
(gen_random_uuid(), 'CLP', '$', 'Chilean peso'),
(gen_random_uuid(), 'CNY', '¥', 'Chinese yuan'),
(gen_random_uuid(), 'COP', '$', 'Colombian peso'),
(gen_random_uuid(), 'CRC', '₡', 'Costa Rican colon'),
(gen_random_uuid(), 'CUP', '₱', 'Cuban peso'),
(gen_random_uuid(), 'CVE', '$', 'Cape Verdean escudo'),
(gen_random_uuid(), 'CZK', 'Kč', 'Czech koruna'),
(gen_random_uuid(), 'DJF', 'Fdj', 'Djiboutian franc'),
(gen_random_uuid(), 'DKK', 'kr', 'Danish krone'),
(gen_random_uuid(), 'DOP', 'RD$', 'Dominican peso'),
(gen_random_uuid(), 'DZD', 'د.ج', 'Algerian dinar'),
(gen_random_uuid(), 'EGP', '£', 'Egyptian pound'),
(gen_random_uuid(), 'ERN', 'Nfk', 'Eritrean nakfa'),
(gen_random_uuid(), 'ETB', 'Br', 'Ethiopian birr'),
(gen_random_uuid(), 'EUR', '€', 'Euro'),
(gen_random_uuid(), 'FJD', '$', 'Fiji dollar'),
(gen_random_uuid(), 'FKP', '£', 'Falkland Islands pound'),
(gen_random_uuid(), 'GBP', '£', 'Pound sterling'),
(gen_random_uuid(), 'GEL', '₾', 'Georgian lari'),
(gen_random_uuid(), 'GHS', '₵', 'Ghanaian cedi'),
(gen_random_uuid(), 'GIP', '£', 'Gibraltar pound'),
(gen_random_uuid(), 'GMD', 'D', 'Gambian dalasi'),
(gen_random_uuid(), 'GNF', 'FG', 'Guinean franc'),
(gen_random_uuid(), 'GTQ', 'Q', 'Guatemalan quetzal'),
(gen_random_uuid(), 'GYD', '$', 'Guyanese dollar'),
(gen_random_uuid(), 'HKD', '$', 'Hong Kong dollar'),
(gen_random_uuid(), 'HNL', 'L', 'Honduran lempira'),
(gen_random_uuid(), 'HRK', 'kn', 'Croatian kuna'),
(gen_random_uuid(), 'HTG', 'G', 'Haitian gourde'),
(gen_random_uuid(), 'HUF', 'Ft', 'Hungarian forint'),
(gen_random_uuid(), 'IDR', 'Rp', 'Indonesian rupiah'),
(gen_random_uuid(), 'ILS', '₪', 'Israeli new shekel'),
(gen_random_uuid(), 'INR', '₹', 'Indian rupee'),
(gen_random_uuid(), 'IQD', 'ع.د', 'Iraqi dinar'),
(gen_random_uuid(), 'IRR', '﷼', 'Iranian rial'),
(gen_random_uuid(), 'ISK', 'kr', 'Icelandic króna'),
(gen_random_uuid(), 'JMD', 'J$', 'Jamaican dollar'),
(gen_random_uuid(), 'JOD', 'د.ا', 'Jordanian dinar'),
(gen_random_uuid(), 'JPY', '¥', 'Japanese yen'),
(gen_random_uuid(), 'KES', 'KSh', 'Kenyan shilling'),
(gen_random_uuid(), 'KGS', 'с', 'Kyrgyzstani som'),
(gen_random_uuid(), 'KHR', '៛', 'Cambodian riel'),
(gen_random_uuid(), 'KMF', 'CF', 'Comoro franc'),
(gen_random_uuid(), 'KPW', '₩', 'North Korean won'),
(gen_random_uuid(), 'KRW', '₩', 'South Korean won'),
(gen_random_uuid(), 'KWD', 'د.ك', 'Kuwaiti dinar'),
(gen_random_uuid(), 'KYD', '$', 'Cayman Islands dollar'),
(gen_random_uuid(), 'KZT', '₸', 'Kazakhstani tenge'),
(gen_random_uuid(), 'LAK', '₭', 'Lao kip'),
(gen_random_uuid(), 'LBP', 'ل.ل', 'Lebanese pound'),
(gen_random_uuid(), 'LKR', 'Rs', 'Sri Lankan rupee'),
(gen_random_uuid(), 'LRD', '$', 'Liberian dollar'),
(gen_random_uuid(), 'LSL', 'L', 'Lesotho loti'),
(gen_random_uuid(), 'LYD', 'ل.د', 'Libyan dinar'),
(gen_random_uuid(), 'MAD', 'د.م.', 'Moroccan dirham'),
(gen_random_uuid(), 'MDL', 'L', 'Moldovan leu'),
(gen_random_uuid(), 'MGA', 'Ar', 'Malagasy ariary'),
(gen_random_uuid(), 'MKD', 'ден', 'Macedonian denar'),
(gen_random_uuid(), 'MMK', 'K', 'Myanmar kyat'),
(gen_random_uuid(), 'MNT', '₮', 'Mongolian tögrög'),
(gen_random_uuid(), 'MOP', 'MOP$', 'Macanese pataca'),
(gen_random_uuid(), 'MRU', 'UM', 'Mauritanian ouguiya'),
(gen_random_uuid(), 'MUR', '₨', 'Mauritian rupee'),
(gen_random_uuid(), 'MVR', '.ރ', 'Maldivian rufiyaa'),
(gen_random_uuid(), 'MWK', 'MK', 'Malawian kwacha'),
(gen_random_uuid(), 'MXN', '$', 'Mexican peso'),
(gen_random_uuid(), 'MYR', 'RM', 'Malaysian ringgit'),
(gen_random_uuid(), 'MZN', 'MT', 'Mozambican metical'),
(gen_random_uuid(), 'NAD', '$', 'Namibian dollar'),
(gen_random_uuid(), 'NGN', '₦', 'Nigerian naira'),
(gen_random_uuid(), 'NIO', 'C$', 'Nicaraguan córdoba'),
(gen_random_uuid(), 'NOK', 'kr', 'Norwegian krone'),
(gen_random_uuid(), 'NPR', '₨', 'Nepalese rupee'),
(gen_random_uuid(), 'NZD', '$', 'New Zealand dollar'),
(gen_random_uuid(), 'OMR', 'ر.ع.', 'Omani rial'),
(gen_random_uuid(), 'PAB', 'B/.', 'Panamanian balboa'),
(gen_random_uuid(), 'PEN', 'S/.', 'Peruvian sol'),
(gen_random_uuid(), 'PGK', 'K', 'Papua New Guinean kina'),
(gen_random_uuid(), 'PHP', '₱', 'Philippine peso'),
(gen_random_uuid(), 'PKR', '₨', 'Pakistani rupee'),
(gen_random_uuid(), 'PLN', 'zł', 'Polish złoty'),
(gen_random_uuid(), 'PYG', '₲', 'Paraguayan guaraní'),
(gen_random_uuid(), 'QAR', 'ر.ق', 'Qatari riyal'),
(gen_random_uuid(), 'RON', 'lei', 'Romanian leu'),
(gen_random_uuid(), 'RSD', 'дин.', 'Serbian dinar'),
(gen_random_uuid(), 'RUB', '₽', 'Russian ruble'),
(gen_random_uuid(), 'RWF', 'FRw', 'Rwandan franc'),
(gen_random_uuid(), 'SAR', 'ر.س', 'Saudi riyal'),
(gen_random_uuid(), 'SBD', '$', 'Solomon Islands dollar'),
(gen_random_uuid(), 'SCR', '₨', 'Seychelles rupee'),
(gen_random_uuid(), 'SDG', 'ج.س.', 'Sudanese pound'),
(gen_random_uuid(), 'SEK', 'kr', 'Swedish krona'),
(gen_random_uuid(), 'SGD', '$', 'Singapore dollar'),
(gen_random_uuid(), 'SHP', '£', 'Saint Helena pound'),
(gen_random_uuid(), 'SLL', 'Le', 'Sierra Leonean leone'),
(gen_random_uuid(), 'SOS', 'S', 'Somali shilling'),
(gen_random_uuid(), 'SRD', '$', 'Surinamese dollar'),
(gen_random_uuid(), 'SSP', '£', 'South Sudanese pound'),
(gen_random_uuid(), 'STN', 'Db', 'São Tomé and Príncipe dobra'),
(gen_random_uuid(), 'SVC', '$', 'Salvadoran colón'),
(gen_random_uuid(), 'SYP', '£', 'Syrian pound'),
(gen_random_uuid(), 'SZL', 'L', 'Swazi lilangeni'),
(gen_random_uuid(), 'THB', '฿', 'Thai baht'),
(gen_random_uuid(), 'TJS', 'ЅМ', 'Tajikistani somoni'),
(gen_random_uuid(), 'TMT', 'm', 'Turkmenistan manat'),
(gen_random_uuid(), 'TND', 'د.ت', 'Tunisian dinar'),
(gen_random_uuid(), 'TOP', 'T$', 'Tongan paʻanga'),
(gen_random_uuid(), 'TRY', '₺', 'Turkish lira'),
(gen_random_uuid(), 'TTD', 'TT$', 'Trinidad and Tobago dollar'),
(gen_random_uuid(), 'TWD', 'NT$', 'New Taiwan dollar'),
(gen_random_uuid(), 'TZS', 'TSh', 'Tanzanian shilling'),
(gen_random_uuid(), 'UAH', '₴', 'Ukrainian hryvnia'),
(gen_random_uuid(), 'UGX', 'USh', 'Ugandan shilling'),
(gen_random_uuid(), 'USD', '$', 'United States dollar'),
(gen_random_uuid(), 'UYU', '$U', 'Uruguayan peso'),
(gen_random_uuid(), 'UZS', 'лв', 'Uzbekistan som'),
(gen_random_uuid(), 'VES', 'Bs', 'Venezuelan bolívar soberano'),
(gen_random_uuid(), 'VND', '₫', 'Vietnamese đồng'),
(gen_random_uuid(), 'VUV', 'VT', 'Vanuatu vatu'),
(gen_random_uuid(), 'WST', 'WS$', 'Samoan tala'),
(gen_random_uuid(), 'XAF', 'FCFA', 'CFA franc BEAC'),
(gen_random_uuid(), 'XCD', '$', 'East Caribbean dollar'),
(gen_random_uuid(), 'XOF', 'CFA', 'CFA franc BCEAO'),
(gen_random_uuid(), 'XPF', '₣', 'CFP franc'),
(gen_random_uuid(), 'YER', '﷼', 'Yemeni rial'),
(gen_random_uuid(), 'ZAR', 'R', 'South African rand'),
(gen_random_uuid(), 'ZMW', 'ZK', 'Zambian kwacha'),
(gen_random_uuid(), 'ZWL', '$', 'Zimbabwean dollar');

-- Insert Currencies
INSERT INTO "TENANT_DUMMY"."tb_currency" (id, code, name, symbol, is_active) VALUES
(gen_random_uuid(), 'THB', 'Thai Baht', '฿', true),
(gen_random_uuid(), 'USD', 'US Dollar', '$', true);

-- Insert Units
INSERT INTO "TENANT_DUMMY"."tb_unit" (id, name, description, is_active) VALUES
(gen_random_uuid(), 'EA', 'Each', true),
(gen_random_uuid(), 'BOX', 'Box', true),
(gen_random_uuid(), 'KG', 'Kilogram', true),
(gen_random_uuid(), 'SET', 'Set', true),
(gen_random_uuid(), 'ROLL', 'Roll', true),
(gen_random_uuid(), 'BTL', 'Bottle', true);

-- Insert Departments
INSERT INTO "TENANT_DUMMY"."tb_department" (id, name, description, is_active) VALUES
(gen_random_uuid(), 'Housekeeping', 'Housekeeping Department', true),
(gen_random_uuid(), 'F&B', 'Food and Beverage Department', true),
(gen_random_uuid(), 'Engineering', 'Engineering and Maintenance', true),
(gen_random_uuid(), 'Front Office', 'Front Office Department', true);

-- Insert Delivery Points
INSERT INTO "TENANT_DUMMY"."tb_delivery_point" (id, name, is_active) VALUES
(gen_random_uuid(), 'Main Kitchen', true),
(gen_random_uuid(), 'Housekeeping Store', true),
(gen_random_uuid(), 'Engineering Workshop', true),
(gen_random_uuid(), 'Front Office', true);

-- Insert Locations
INSERT INTO "TENANT_DUMMY"."tb_location" (id, name, location_type, description, is_active) VALUES
(gen_random_uuid(), 'Main Warehouse', 'inventory', 'Main Hotel Storage', true),
(gen_random_uuid(), 'HK Store Room', 'inventory', 'Housekeeping Storage', true),
(gen_random_uuid(), 'Kitchen Storage', 'inventory', 'Main Kitchen Storage', true),
(gen_random_uuid(), 'Mini Bar Store', 'inventory', 'Mini Bar Items Storage', true);

-- Insert Product Categories
INSERT INTO "TENANT_DUMMY"."tb_product_category" (id, code, name, description, is_active) VALUES
(gen_random_uuid(), 'ROOM', 'Room Supplies', 'Guest Room Related Items', true),
(gen_random_uuid(), 'F&B', 'Food and Beverage', 'F&B Related Items', true),
(gen_random_uuid(), 'MAINT', 'Maintenance', 'Maintenance Supplies', true),
(gen_random_uuid(), 'OFF', 'Office Supplies', 'Office Related Items', true);

-- Insert Product Sub Categories
INSERT INTO "TENANT_DUMMY"."tb_product_sub_category" (id, code, name, description, product_category_id, is_active) VALUES
(gen_random_uuid(), 'AMENITY', 'Guest Amenities', 'In-room Guest Amenities', (SELECT id FROM "TENANT_DUMMY"."tb_product_category" WHERE code = 'ROOM'), true),
(gen_random_uuid(), 'LINEN', 'Linen Items', 'Bed and Bath Linen', (SELECT id FROM "TENANT_DUMMY"."tb_product_category" WHERE code = 'ROOM'), true),
(gen_random_uuid(), 'MINIBAR', 'Mini Bar Items', 'In-room Mini Bar Products', (SELECT id FROM "TENANT_DUMMY"."tb_product_category" WHERE code = 'F&B'), true),
(gen_random_uuid(), 'CLEANING', 'Cleaning Supplies', 'Cleaning Materials', (SELECT id FROM "TENANT_DUMMY"."tb_product_category" WHERE code = 'MAINT'), true);

-- Insert Product Item group
INSERT INTO "TENANT_DUMMY"."tb_product_item_group" (id, code, name, description, product_subcategory_id, is_active) VALUES
(gen_random_uuid(), 'BATH', 'Bathroom Amenities', 'Bathroom related amenities', (SELECT id FROM "TENANT_DUMMY"."tb_product_sub_category" WHERE code = 'AMENITY'), true),
(gen_random_uuid(), 'BODY', 'Body Care', 'Body care amenities', (SELECT id FROM "TENANT_DUMMY"."tb_product_sub_category" WHERE code = 'AMENITY'), true),
(gen_random_uuid(), 'BED', 'Bedding', 'Bed related linen', (SELECT id FROM "TENANT_DUMMY"."tb_product_sub_category" WHERE code = 'LINEN'), true),
(gen_random_uuid(), 'BATH_LIN', 'Bathroom Linen', 'Bathroom related linen', (SELECT id FROM "TENANT_DUMMY"."tb_product_sub_category" WHERE code = 'LINEN'), true),
(gen_random_uuid(), 'DRINK', 'Beverages', 'Minibar drinks', (SELECT id FROM "TENANT_DUMMY"."tb_product_sub_category" WHERE code = 'MINIBAR'), true),
(gen_random_uuid(), 'SNACK', 'Snacks', 'Minibar snacks', (SELECT id FROM "TENANT_DUMMY"."tb_product_sub_category" WHERE code = 'MINIBAR'), true),
(gen_random_uuid(), 'FLOOR', 'Floor Cleaning', 'Floor cleaning supplies', (SELECT id FROM "TENANT_DUMMY"."tb_product_sub_category" WHERE code = 'CLEANING'), true),
(gen_random_uuid(), 'SURFACE', 'Surface Cleaning', 'Surface cleaning supplies', (SELECT id FROM "TENANT_DUMMY"."tb_product_sub_category" WHERE code = 'CLEANING'), true);



-- Insert Products
INSERT INTO "TENANT_DUMMY"."tb_product" (id, code, name, description, primary_unit_id, is_active) VALUES
(gen_random_uuid(), 'AM001', 'Shower Gel 30ml', 'Guest Amenity Shower Gel', (SELECT id FROM "TENANT_DUMMY"."tb_unit" WHERE name = 'EA'), true),
(gen_random_uuid(), 'AM002', 'Shampoo 30ml', 'Guest Amenity Shampoo', (SELECT id FROM "TENANT_DUMMY"."tb_unit" WHERE name = 'EA'), true),
(gen_random_uuid(), 'LN001', 'Towel', 'Guest Room Towel', (SELECT id FROM "TENANT_DUMMY"."tb_unit" WHERE name = 'EA'), true),
(gen_random_uuid(), 'LN002', 'Bed Sheet', 'Guest Room Bed Sheet', (SELECT id FROM "TENANT_DUMMY"."tb_unit" WHERE name = 'EA'), true),
(gen_random_uuid(), 'MB001', 'Water Bottle', 'Minibar Water Bottle', (SELECT id FROM "TENANT_DUMMY"."tb_unit" WHERE name = 'EA'), true),
(gen_random_uuid(), 'CL001', 'Floor Cleaner', 'Floor Cleaning Solution', (SELECT id FROM "TENANT_DUMMY"."tb_unit" WHERE name = 'BTL'), true);


-- Insert Product Info
INSERT INTO "TENANT_DUMMY"."tb_product_info" (id, product_id, product_item_group_id, price, info) VALUES
(gen_random_uuid(), 
 (SELECT id FROM "TENANT_DUMMY"."tb_product" WHERE code = 'AM001'),
 (SELECT id FROM "TENANT_DUMMY"."tb_product_item_group" WHERE code = 'BATH'),
 15.00,
 '{"brand": "Luxury Bath", "supplier": "ABC Amenities", "min_stock": 100}'
),
(gen_random_uuid(),
 (SELECT id FROM "TENANT_DUMMY"."tb_product" WHERE code = 'AM002'),
 (SELECT id FROM "TENANT_DUMMY"."tb_product_item_group" WHERE code = 'BATH'),
 15.00, 
 '{"brand": "Luxury Bath", "supplier": "ABC Amenities", "min_stock": 100}'
),
(gen_random_uuid(),
 (SELECT id FROM "TENANT_DUMMY"."tb_product" WHERE code = 'LN001'),
 (SELECT id FROM "TENANT_DUMMY"."tb_product_item_group" WHERE code = 'BATH_LIN'),
 120.00,
 '{"brand": "Premium Textile", "supplier": "XYZ Linen", "min_stock": 50}'
),
(gen_random_uuid(),
 (SELECT id FROM "TENANT_DUMMY"."tb_product" WHERE code = 'LN002'),
 (SELECT id FROM "TENANT_DUMMY"."tb_product_item_group" WHERE code = 'BED'),
 250.00,
 '{"brand": "Premium Textile", "supplier": "XYZ Linen", "min_stock": 30}'
),
(gen_random_uuid(),
 (SELECT id FROM "TENANT_DUMMY"."tb_product" WHERE code = 'MB001'),
 (SELECT id FROM "TENANT_DUMMY"."tb_product_item_group" WHERE code = 'DRINK'),
 25.00,
 '{"brand": "Crystal Clear", "supplier": "Water Co Ltd", "min_stock": 200}'
),
(gen_random_uuid(),
 (SELECT id FROM "TENANT_DUMMY"."tb_product" WHERE code = 'CL001'),
 (SELECT id FROM "TENANT_DUMMY"."tb_product_item_group" WHERE code = 'FLOOR'),
 180.00,
 '{"brand": "CleanPro", "supplier": "Cleaning Supply Co", "min_stock": 20}'
);
